const MENU = [
  {
    "id": "1-1",
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers",
    "name_ru": "Мясное плато (казы, жая, жал)",
    "name_kz": "Ет ассортиі (қазы, жая, жал)",
    "name_en": "Meat platter (kazy, zhaya, zhal)",
    "price": 4990,
    "weight": "250g",
    "composition_ru": "Традиционные мясные деликатесы: казы, жая, жал",
    "composition_kz": "Дәстүрлі ет деликатестері: қазы, жая, жал",
    "composition_en": "Traditional meat delicacies: kazy, zhaya, zhal",
    "note": ""
  },
  {
    "id": "1-2",
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers",
    "name_ru": "Домашние соленья",
    "name_kz": "Үй тұздықтары",
    "name_en": "Homemade pickles",
    "price": 2890,
    "weight": "300g",
    "composition_ru": "Ассорти из домашних солений",
    "composition_kz": "Үй тұздықтарының ассортиі",
    "composition_en": "Assorted homemade pickles",
    "note": ""
  },
  {
    "id": "1-3",
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers",
    "name_ru": "Овощная нарезка",
    "name_kz": "Көкөніс тілімі",
    "name_en": "Vegetable platter",
    "price": 2890,
    "weight": "350g",
    "composition_ru": "Свежие сезонные овощи",
    "composition_kz": "Балғын маусымдық көкөністер",
    "composition_en": "Fresh seasonal vegetables",
    "note": ""
  },
  {
    "id": "2-3",
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "name_ru": "Цезарь с курицей",
    "name_kz": "Тауық еті қосылған Цезарь",
    "name_en": "Chicken Caesar",
    "price": 2590,
    "weight": "280g",
    "composition_ru": "Айсберг, куриное филе, соус цезарь, пармезан, гренки",
    "composition_kz": "Айсберг, тауық филесі, цезарь соусы, пармезан, кептірілген нан",
    "composition_en": "Iceberg, chicken fillet, Caesar sauce, parmesan, croutons",
    "note": ""
  },
  {
    "id": "2-7",
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "name_ru": "Салат с креветками и рукколой",
    "name_kz": "Креветкалар мен руккола қосылған салат",
    "name_en": "Shrimp and arugula salad",
    "price": 3990,
    "weight": "220g",
    "composition_ru": "Креветки, руккола, черри, кедровые орехи, пармезан",
    "composition_kz": "Креветкалар, руккола, черри, балқарағай жаңғақтары, пармезан",
    "composition_en": "Shrimp, arugula, cherry tomatoes, pine nuts, parmesan",
    "note": ""
  },
  {
    "id": "5-4",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Том Ям",
    "name_kz": "Том Ям",
    "name_en": "Tom Yum",
    "price": 3590,
    "weight": "350ml",
    "composition_ru": "Креветки, кальмары, грибы, кокосовое молоко, рис",
    "composition_kz": "Креветкалар, кальмарлар, саңырауқұлақтар, кокос сүті, күріш",
    "composition_en": "Shrimp, squid, mushrooms, coconut milk, rice",
    "note": "Острое блюдо"
  },
  {
    "id": "13-1",
    "category_ru": "Безалкогольные напитки",
    "category_kz": "Алкогольсіз сусындар",
    "category_en": "Soft Drinks",
    "name_ru": "Фирменные лимонады",
    "name_kz": "Фирменді лимонадтар",
    "name_en": "Signature lemonades",
    "price": 2990,
    "weight": "1L",
    "composition_ru": "Вишня-Виноград / Киви-Грейпфрут / Маракуйя-Ананас / Нектар",
    "composition_kz": "Шие-Жүзім / Киви-Грейпфрут / Маракуйя-Ананас / Нектар",
    "composition_en": "Cherry-Grape / Kiwi-Grapefruit / Passion fruit-Pineapple / Nectar",
    "note": ""
  }
];
