const MENU_CATEGORIES = {
  "sets": {
    "category_ru": "Сеты",
    "category_kz": "Сеттер",
    "category_en": "Sets"
  },
  "cold": {
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers"
  },
  "salads": {
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads"
  },
  "hot_starters": {
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тіскебасарлар",
    "category_en": "Hot Appetizers"
  },
  "soups": {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups"
  },
  "mains": {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses"
  },
  "pasta": {
    "category_ru": "Паста",
    "category_kz": "Паста",
    "category_en": "Pasta"
  },
  "pizza_bakery": {
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және пісірмелер",
    "category_en": "Pizza & Bakery"
  },
  "grill": {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill"
  },
  "beer_snacks": {
    "category_ru": "Закуски к пиву",
    "category_kz": "Сыраға арналған тіскебасарлар",
    "category_en": "Beer Snacks"
  },
  "sharing": {
    "category_ru": "Для компании",
    "category_kz": "Компанияға арналған",
    "category_en": "For Sharing"
  },
  "sides_sauces": {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces"
  },
  "desserts_fruit": {
    "category_ru": "Десерты и фрукты",
    "category_kz": "Десерттер мен жемістер",
    "category_en": "Desserts & Fruit"
  },
  "white_wine_glass": {
    "category_ru": "Белое по бокалам",
    "category_kz": "Бокалмен ақ шарап",
    "category_en": "White Wine by the Glass"
  },
  "red_wine_glass": {
    "category_ru": "Красное по бокалам",
    "category_kz": "Бокалмен қызыл шарап",
    "category_en": "Red Wine by the Glass"
  },
  "rose_wine_glass": {
    "category_ru": "Розовое по бокалам",
    "category_kz": "Бокалмен қызғылт шарап",
    "category_en": "Rosé Wine by the Glass"
  },
  "nonalcoholic_wine": {
    "category_ru": "Безалкогольное вино",
    "category_kz": "Алкогольсіз шарап",
    "category_en": "Non-Alcoholic Wine"
  },
  "sparkling_wine": {
    "category_ru": "Игристое вино",
    "category_kz": "Көпіршікті шарап",
    "category_en": "Sparkling Wine"
  },
  "white_wine": {
    "category_ru": "Белое вино",
    "category_kz": "Ақ шарап",
    "category_en": "White Wine"
  },
  "red_wine": {
    "category_ru": "Красное вино",
    "category_kz": "Қызыл шарап",
    "category_en": "Red Wine"
  },
  "bottled_beer": {
    "category_ru": "Бутылочное пиво",
    "category_kz": "Бөтелкедегі сыра",
    "category_en": "Bottled Beer"
  },
  "draft_beer": {
    "category_ru": "Разливное пиво",
    "category_kz": "Құймалы сыра",
    "category_en": "Draft Beer"
  },
  "vodka": {
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka"
  },
  "whisky": {
    "category_ru": "Виски",
    "category_kz": "Виски",
    "category_en": "Whisky"
  },
  "cognac_brandy_calvados": {
    "category_ru": "Коньяк, бренди и кальвадос",
    "category_kz": "Коньяк, бренди және кальвадос",
    "category_en": "Cognac, Brandy & Calvados"
  },
  "gin": {
    "category_ru": "Джин",
    "category_kz": "Джин",
    "category_en": "Gin"
  },
  "rum": {
    "category_ru": "Ром",
    "category_kz": "Ром",
    "category_en": "Rum"
  },
  "tequila": {
    "category_ru": "Текила",
    "category_kz": "Текила",
    "category_en": "Tequila"
  },
  "lemonades": {
    "category_ru": "Лимонады",
    "category_kz": "Лимонадтар",
    "category_en": "Lemonades"
  },
  "soft_drinks": {
    "category_ru": "Вода и прохладительные напитки",
    "category_kz": "Су және салқын сусындар",
    "category_en": "Water & Soft Drinks"
  },
  "signature_tea": {
    "category_ru": "Авторский чай",
    "category_kz": "Авторлық шай",
    "category_en": "Signature Tea"
  },
  "loose_leaf_tea": {
    "category_ru": "Листовой чай",
    "category_kz": "Жапырақты шай",
    "category_en": "Loose-Leaf Tea"
  },
  "tea_addons": {
    "category_ru": "Добавки к чаю",
    "category_kz": "Шайға қосымшалар",
    "category_en": "Tea Add-ons"
  }
};

const MENU = [
  {
    "id": "k-set-01-pizza-lemonade",
    "type": "kitchen",
    "category_id": "sets",
    "name_ru": "Сет 01 · Пицца и лимонад",
    "name_kz": "Сет 01 · Пицца мен лимонад",
    "name_en": "Set 01 · Pizza & Lemonade",
    "price": 7990,
    "weight": "",
    "composition_ru": "Дымная чаша, пицца с курицей и грибами, лимонад",
    "composition_kz": "Түтінді тостаған, тауық еті мен саңырауқұлақ қосылған пицца, лимонад",
    "composition_en": "Smoke bowl, chicken and mushroom pizza, lemonade",
    "source_article": "set-01",
    "category_ru": "Сеты",
    "category_kz": "Сеттер",
    "category_en": "Sets"
  },
  {
    "id": "k-set-02-club-lemonade",
    "type": "kitchen",
    "category_id": "sets",
    "name_ru": "Сет 02 · Клаб-сэндвич и лимонад",
    "name_kz": "Сет 02 · Клаб-сэндвич пен лимонад",
    "name_en": "Set 02 · Club Sandwich & Lemonade",
    "price": 7990,
    "weight": "",
    "composition_ru": "Дымная чаша, клаб-сэндвич с курицей, лимонад",
    "composition_kz": "Түтінді тостаған, тауық еті қосылған клаб-сэндвич, лимонад",
    "composition_en": "Smoke bowl, chicken club sandwich, lemonade",
    "source_article": "set-02",
    "category_ru": "Сеты",
    "category_kz": "Сеттер",
    "category_en": "Sets"
  },
  {
    "id": "k-set-03-tea-fruit",
    "type": "kitchen",
    "category_id": "sets",
    "name_ru": "Сет 03 · Чай и фрукты",
    "name_kz": "Сет 03 · Шай мен жемістер",
    "name_en": "Set 03 · Tea & Fruit",
    "price": 6990,
    "weight": "",
    "composition_ru": "Дымная чаша, чай и сезонные фрукты",
    "composition_kz": "Түтінді тостаған, шай және маусымдық жемістер",
    "composition_en": "Smoke bowl, tea and seasonal fruit",
    "source_article": "set-03",
    "category_ru": "Сеты",
    "category_kz": "Сеттер",
    "category_en": "Sets"
  },
  {
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers",
    "id": "k-00056-145",
    "type": "kitchen",
    "category_id": "cold",
    "name_ru": "Мясное плато",
    "name_kz": "Ет табағы",
    "name_en": "Meat Platter",
    "price": 4990,
    "weight": "300g",
    "composition_ru": "Казы, жая, язык",
    "composition_kz": "Қазы, жая, тіл",
    "composition_en": "Kazy, zhaya and tongue",
    "source_article": "00056"
  },
  {
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers",
    "id": "k-00124-148",
    "type": "kitchen",
    "category_id": "cold",
    "name_ru": "Сырное плато",
    "name_kz": "Ірімшік табағы",
    "name_en": "Cheese Platter",
    "price": 4990,
    "weight": "350g",
    "composition_ru": "Ассорти сыров, орехи, виноград и мёд",
    "composition_kz": "Ірімшіктер ассортиі, жаңғақ, жүзім және бал",
    "composition_en": "Assorted cheeses, nuts, grapes and honey",
    "source_article": "00124"
  },
  {
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers",
    "id": "k-00059-147",
    "type": "kitchen",
    "category_id": "cold",
    "name_ru": "Рыбное ассорти",
    "name_kz": "Балық ассортиі",
    "name_en": "Fish Platter",
    "price": 5590,
    "weight": "300g",
    "composition_ru": "Ассорти рыбы, лимон, маслины и зелень",
    "composition_kz": "Балық ассортиі, лимон, зәйтүн және көк шөптер",
    "composition_en": "Assorted fish, lemon, olives and fresh herbs",
    "source_article": "00059"
  },
  {
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers",
    "id": "k-00060-144",
    "type": "kitchen",
    "category_id": "cold",
    "name_ru": "Капрезе",
    "name_kz": "Капрезе",
    "name_en": "Caprese",
    "price": 2790,
    "weight": "320g",
    "composition_ru": "Томаты, моцарелла, базилик и соус песто",
    "composition_kz": "Қызанақ, моцарелла, базилик және песто соусы",
    "composition_en": "Tomatoes, mozzarella, basil and pesto",
    "source_article": "00060"
  },
  {
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers",
    "id": "k-00058-146",
    "type": "kitchen",
    "category_id": "cold",
    "name_ru": "Овощная нарезка",
    "name_kz": "Көкөніс ассортиі",
    "name_en": "Fresh Vegetable Platter",
    "price": 2890,
    "weight": "450g",
    "composition_ru": "Свежие томаты, огурцы, сладкий перец, редис, сыр фета",
    "composition_kz": "Балғын қызанақ, қияр, тәтті бұрыш, шалғам және фета ірімшігі",
    "composition_en": "Fresh tomatoes, cucumbers, sweet peppers, radish and feta cheese",
    "source_article": "00058"
  },
  {
    "category_ru": "Холодные закуски",
    "category_kz": "Салқын тіскебасарлар",
    "category_en": "Cold Appetizers",
    "id": "k-00057-143",
    "type": "kitchen",
    "category_id": "cold",
    "name_ru": "Домашние соленья",
    "name_kz": "Үй тұздықтары",
    "name_en": "Homemade Pickles",
    "price": 2890,
    "weight": "300g",
    "composition_ru": "Солёные огурцы, томаты, капуста и сезонные домашние соленья",
    "composition_kz": "Тұздалған қияр, қызанақ, қырыққабат және маусымдық үй тұздықтары",
    "composition_en": "Pickled cucumbers, tomatoes, cabbage and seasonal house pickles",
    "source_article": "00057"
  },
  {
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "id": "k-00034-126",
    "type": "kitchen",
    "category_id": "salads",
    "name_ru": "Хрустящие баклажаны",
    "name_kz": "Қытырлақ баялды",
    "name_en": "Crispy Eggplant Salad",
    "price": 2790,
    "weight": "350g",
    "composition_ru": "Хрустящие баклажаны, томаты, зелень и кисло-сладкий соус",
    "composition_kz": "Қытырлақ баялды, қызанақ, көк шөптер және тәтті-қышқыл соус",
    "composition_en": "Crispy eggplant, tomatoes, fresh herbs and sweet-and-sour sauce",
    "source_article": "00034",
    "tags": [
      "vegetarian"
    ],
    "featured": true
  },
  {
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "id": "k-00033-127",
    "type": "kitchen",
    "category_id": "salads",
    "name_ru": "Цезарь с курицей",
    "name_kz": "Тауық еті қосылған Цезарь",
    "name_en": "Chicken Caesar Salad",
    "price": 2590,
    "weight": "370g",
    "composition_ru": "Куриное филе, салат романо, томаты, пармезан, крутоны и соус Цезарь",
    "composition_kz": "Тауық филесі, романо салаты, қызанақ, пармезан, крутондар және Цезарь соусы",
    "composition_en": "Chicken fillet, romaine lettuce, tomatoes, Parmesan, croutons and Caesar dressing",
    "source_article": "00033"
  },
  {
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "id": "k-00039-123",
    "type": "kitchen",
    "category_id": "salads",
    "name_ru": "Салат с креветками и руколой",
    "name_kz": "Асшаян мен рукола салаты",
    "name_en": "Shrimp & Arugula Salad",
    "price": 3990,
    "weight": "370g",
    "composition_ru": "Креветки, рукола, томаты черри, пармезан и малиновая заправка",
    "composition_kz": "Асшаян, рукола, черри қызанағы, пармезан және таңқурайлы тұздық",
    "composition_en": "Shrimp, arugula, cherry tomatoes, Parmesan and raspberry dressing",
    "source_article": "00039"
  },
  {
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "id": "k-00038-125",
    "type": "kitchen",
    "category_id": "salads",
    "name_ru": "Тёплый салат с кониной",
    "name_kz": "Жылқы еті қосылған жылы салат",
    "name_en": "Warm Horse Meat Salad",
    "price": 2990,
    "weight": "385g",
    "composition_ru": "Конина, микс салатов, томаты, овощи и фирменная заправка",
    "composition_kz": "Жылқы еті, салат миксі, қызанақ, көкөністер және фирмалық тұздық",
    "composition_en": "Horse meat, mixed greens, tomatoes, vegetables and house dressing",
    "source_article": "00038"
  },
  {
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "id": "k-00035-122",
    "type": "kitchen",
    "category_id": "salads",
    "name_ru": "Греческий салат",
    "name_kz": "Грек салаты",
    "name_en": "Greek Salad",
    "price": 2490,
    "weight": "350g",
    "composition_ru": "Томаты, огурцы, сладкий перец, фета, маслины и оливковая заправка",
    "composition_kz": "Қызанақ, қияр, тәтті бұрыш, фета, зәйтүн және зәйтүн майлы тұздық",
    "composition_en": "Tomatoes, cucumbers, sweet peppers, feta, olives and olive-oil dressing",
    "source_article": "00035"
  },
  {
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "id": "k-00031-124",
    "type": "kitchen",
    "category_id": "salads",
    "name_ru": "Свежий овощной салат",
    "name_kz": "Балғын көкөніс салаты",
    "name_en": "Fresh Vegetable Salad",
    "price": 1990,
    "weight": "300g",
    "composition_ru": "Томаты, огурцы, сладкий перец, зелень и лёгкая заправка",
    "composition_kz": "Қызанақ, қияр, тәтті бұрыш, көк шөптер және жеңіл тұздық",
    "composition_en": "Tomatoes, cucumbers, sweet peppers, herbs and a light dressing",
    "source_article": "00031"
  },
  {
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "id": "k-00032-121",
    "type": "kitchen",
    "category_id": "salads",
    "name_ru": "Аччик-чучук",
    "name_kz": "Аччик-чучук",
    "name_en": "Achichuk",
    "price": 1790,
    "weight": "350g",
    "composition_ru": "Томаты, репчатый лук, зелень и специи",
    "composition_kz": "Қызанақ, пияз, көк шөптер және дәмдеуіштер",
    "composition_en": "Tomatoes, onions, fresh herbs and spices",
    "source_article": "00032"
  },
  {
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тіскебасарлар",
    "category_en": "Hot Appetizers",
    "id": "k-00125-96",
    "type": "kitchen",
    "category_id": "hot_starters",
    "name_ru": "Креветки темпура",
    "name_kz": "Темпура асшаяндары",
    "name_en": "Shrimp Tempura",
    "price": 3290,
    "weight": "180g",
    "composition_ru": "Креветки в хрустящем кляре темпура с соусом",
    "composition_kz": "Қытырлақ темпура қамырындағы асшаяндар, соуспен беріледі",
    "composition_en": "Shrimp in crisp tempura batter, served with dipping sauce",
    "source_article": "00125"
  },
  {
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тіскебасарлар",
    "category_en": "Hot Appetizers",
    "id": "k-00061-94",
    "type": "kitchen",
    "category_id": "hot_starters",
    "name_ru": "Кесадилья с курицей",
    "name_kz": "Тауық еті қосылған кесадилья",
    "name_en": "Chicken Quesadilla",
    "price": 2990,
    "weight": "350g",
    "composition_ru": "Тортилья, куриное филе, соус сальса, сыр, сметана",
    "composition_kz": "Тортилья, тауық филесі, сальса соусы, ірімшік және қаймақ",
    "composition_en": "Tortilla, chicken fillet, salsa, cheese and sour cream",
    "source_article": "00061"
  },
  {
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тіскебасарлар",
    "category_en": "Hot Appetizers",
    "id": "k-00065-95",
    "type": "kitchen",
    "category_id": "hot_starters",
    "name_ru": "Клаб-сэндвич с курицей",
    "name_kz": "Тауық еті қосылған клаб-сэндвич",
    "name_en": "Chicken Club Sandwich",
    "price": 3190,
    "weight": "350g",
    "composition_ru": "Куриное филе, тостовый хлеб, овощи, сыр, соус и картофель фри",
    "composition_kz": "Тауық филесі, тост наны, көкөністер, ірімшік, соус және фри",
    "composition_en": "Chicken fillet, toasted bread, vegetables, cheese, sauce and fries",
    "source_article": "00065"
  },
  {
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тіскебасарлар",
    "category_en": "Hot Appetizers",
    "id": "k-00062-98",
    "type": "kitchen",
    "category_id": "hot_starters",
    "name_ru": "Чебуреки",
    "name_kz": "Чебурек",
    "name_en": "Chebureki",
    "price": 2590,
    "weight": "250g",
    "composition_ru": "Хрустящее тесто с сочной мясной начинкой",
    "composition_kz": "Қытырлақ қамыр және шырынды ет салмасы",
    "composition_en": "Crisp pastry filled with seasoned minced meat",
    "source_article": "00062"
  },
  {
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тіскебасарлар",
    "category_en": "Hot Appetizers",
    "id": "k-00100-97",
    "type": "kitchen",
    "category_id": "hot_starters",
    "name_ru": "Наггетсы куриные",
    "name_kz": "Тауық наггетстары",
    "name_en": "Chicken Nuggets",
    "price": 1690,
    "weight": "200g",
    "composition_ru": "Куриное филе в хрустящей панировке с соусом",
    "composition_kz": "Қытырлақ панировкадағы тауық филесі, соуспен беріледі",
    "composition_en": "Breaded chicken pieces served with dipping sauce",
    "source_article": "00100"
  },
  {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "id": "k-00044-140",
    "type": "kitchen",
    "category_id": "soups",
    "name_ru": "Том Ям",
    "name_kz": "Том Ям",
    "name_en": "Tom Yum",
    "price": 3590,
    "weight": "350ml",
    "composition_ru": "Креветки, грибы, томаты, лайм, кокосовое молоко и пряный бульон",
    "composition_kz": "Асшаян, саңырауқұлақ, қызанақ, лайм, кокос сүті және ащы хош иісті сорпа",
    "composition_en": "Shrimp, mushrooms, tomatoes, lime, coconut milk and aromatic spicy broth",
    "source_article": "00044",
    "tags": [
      "spicy"
    ],
    "note": "Острое блюдо",
    "thumb_image": "assets/menu/thumbs/5-4.webp",
    "full_image": "assets/menu/full/5-4.webp",
    "image": "assets/menu/items/5-4.webp"
  },
  {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "id": "k-00045-138",
    "type": "kitchen",
    "category_id": "soups",
    "name_ru": "Рамен с говядиной",
    "name_kz": "Сиыр еті қосылған рамен",
    "name_en": "Beef Ramen",
    "price": 3590,
    "weight": "450ml",
    "composition_ru": "Лапша рамен, говядина, насыщенный бульон, яйцо, овощи и зелень",
    "composition_kz": "Рамен кеспесі, сиыр еті, қою сорпа, жұмыртқа, көкөністер және көк шөптер",
    "composition_en": "Ramen noodles, beef, rich broth, egg, vegetables and herbs",
    "source_article": "00045",
    "featured": true
  },
  {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "id": "k-00049-142",
    "type": "kitchen",
    "category_id": "soups",
    "name_ru": "Шорпа",
    "name_kz": "Сорпа",
    "name_en": "Shorpa",
    "price": 3290,
    "weight": "400ml",
    "composition_ru": "Мясо, картофель, лук, томаты и наваристый бульон",
    "composition_kz": "Ет, картоп, пияз, қызанақ және қою сорпа",
    "composition_en": "Meat, potatoes, onions, tomatoes and hearty broth",
    "source_article": "00049"
  },
  {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "id": "k-00046-139",
    "type": "kitchen",
    "category_id": "soups",
    "name_ru": "Рамен с курицей",
    "name_kz": "Тауық еті қосылған рамен",
    "name_en": "Chicken Ramen",
    "price": 3290,
    "weight": "450ml",
    "composition_ru": "Лапша рамен, куриное филе, насыщенный бульон, яйцо, овощи и зелень",
    "composition_kz": "Рамен кеспесі, тауық филесі, қою сорпа, жұмыртқа, көкөністер және көк шөптер",
    "composition_en": "Ramen noodles, chicken fillet, rich broth, egg, vegetables and herbs",
    "source_article": "00046",
    "featured": true
  },
  {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "id": "k-00128-135",
    "type": "kitchen",
    "category_id": "soups",
    "name_ru": "Окрошка с мясом (сезонная)",
    "name_kz": "Ет қосылған окрошка (маусымдық)",
    "name_en": "Okroshka with Meat (Seasonal)",
    "price": 2390,
    "weight": "350ml",
    "composition_ru": "Мясо, картофель, огурцы, яйцо, зелень и охлаждённая кисломолочная основа",
    "composition_kz": "Ет, картоп, қияр, жұмыртқа, көк шөптер және салқын қышқыл сүтті негіз",
    "composition_en": "Meat, potatoes, cucumbers, egg, herbs and a chilled cultured-dairy base",
    "source_article": "00128"
  },
  {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "id": "k-00048-137",
    "type": "kitchen",
    "category_id": "soups",
    "name_ru": "Пельмени с бульоном",
    "name_kz": "Сорпалы тұшпара",
    "name_en": "Dumplings in Broth",
    "price": 1990,
    "weight": "300g",
    "composition_ru": "Домашние пельмени с мясной начинкой в бульоне",
    "composition_kz": "Ет салмасы бар үй тұшпарасы, сорпамен",
    "composition_en": "House-made meat dumplings served in broth",
    "source_article": "00048"
  },
  {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "id": "k-00050-136",
    "type": "kitchen",
    "category_id": "soups",
    "name_ru": "Пельмени без бульона",
    "name_kz": "Сорпасыз тұшпара",
    "name_en": "Dumplings without Broth",
    "price": 1990,
    "weight": "300g",
    "composition_ru": "Домашние пельмени с мясной начинкой",
    "composition_kz": "Ет салмасы бар үй тұшпарасы",
    "composition_en": "House-made dumplings with a meat filling",
    "source_article": "00050"
  },
  {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "id": "k-00047-141",
    "type": "kitchen",
    "category_id": "soups",
    "name_ru": "Чечевичный крем-суп",
    "name_kz": "Жасымық крем-сорпасы",
    "name_en": "Creamy Lentil Soup",
    "price": 1990,
    "weight": "350ml",
    "composition_ru": "Красная чечевица, овощи, сливки и ароматные специи",
    "composition_kz": "Қызыл жасымық, көкөністер, кілегей және хош иісті дәмдеуіштер",
    "composition_en": "Red lentils, vegetables, cream and aromatic spices",
    "source_article": "00047"
  },
  {
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "id": "k-00042-134",
    "type": "kitchen",
    "category_id": "soups",
    "name_ru": "Куриный суп с лапшой",
    "name_kz": "Кеспелі тауық сорпасы",
    "name_en": "Chicken Noodle Soup",
    "price": 1590,
    "weight": "350ml",
    "composition_ru": "Куриный бульон, куриное филе, домашняя лапша, морковь и зелень",
    "composition_kz": "Тауық сорпасы, тауық филесі, үй кеспесі, сәбіз және көк шөптер",
    "composition_en": "Chicken broth, chicken fillet, homemade noodles, carrots and herbs",
    "source_article": "00042"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00131-84",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Бургер с говядиной",
    "name_kz": "Сиыр еті қосылған бургер",
    "name_en": "Beef Burger",
    "price": 3590,
    "weight": "420g",
    "composition_ru": "Булочка, говяжья котлета, сыр, салат, томаты, соус и картофель фри",
    "composition_kz": "Тоқаш, сиыр етінен котлет, ірімшік, салат, қызанақ, соус және фри",
    "composition_en": "Bun, beef patty, cheese, lettuce, tomatoes, sauce and fries",
    "source_article": "00131"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00132-86",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Бургер, грибной стаут",
    "name_kz": "«Грибной стаут» бургері",
    "name_en": "Mushroom Stout Burger",
    "price": 4390,
    "weight": "430g",
    "composition_ru": "Булочка, говяжья котлета, шампиньоны, сыр, фирменный грибной соус и картофель фри",
    "composition_kz": "Тоқаш, сиыр етінен котлет, шампиньон, ірімшік, фирмалық саңырауқұлақ соусы және фри",
    "composition_en": "Bun, beef patty, mushrooms, cheese, house mushroom sauce and fries",
    "source_article": "00132"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00130-85",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Бургер с курицей",
    "name_kz": "Тауық бургері",
    "name_en": "Chicken Burger",
    "price": 3290,
    "weight": "400g",
    "composition_ru": "Булочка, куриная котлета, сыр, салат, томаты, соус и картофель фри",
    "composition_kz": "Тоқаш, тауық котлеті, ірімшік, салат, қызанақ, соус және фри",
    "composition_en": "Bun, chicken patty, cheese, lettuce, tomatoes, sauce and fries",
    "source_article": "00130"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00022-83",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Бефстроганов с пюре",
    "name_kz": "Картоп езбесімен бефстроганов",
    "name_en": "Beef Stroganoff with Mashed Potatoes",
    "price": 3290,
    "weight": "380g",
    "composition_ru": "Говядина, шампиньоны, сливочный соус и картофельное пюре",
    "composition_kz": "Сиыр еті, шампиньон, кілегейлі соус және картоп езбесі",
    "composition_en": "Beef, mushrooms, creamy sauce and mashed potatoes",
    "source_article": "00022"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00005-87",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Говядина по-тайски с рисом",
    "name_kz": "Күрішпен берілетін тайша сиыр еті",
    "name_en": "Thai-Style Beef with Rice",
    "price": 3290,
    "weight": "380g",
    "composition_ru": "Говядина, овощи, пряный азиатский соус и рис",
    "composition_kz": "Сиыр еті, көкөністер, дәмдеуішті азиялық соус және күріш",
    "composition_en": "Beef, vegetables, aromatic Asian-style sauce and rice",
    "source_article": "00005"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00023-92",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Куриная грудка в сырно-сливочном соусе",
    "name_kz": "Ірімшік пен кілегей тұздығындағы тауықтың төс еті",
    "name_en": "Chicken Breast with Creamy Cheese Sauce",
    "price": 3290,
    "weight": "350g",
    "composition_ru": "Куриная грудка, сырно-сливочный соус и гарнир",
    "composition_kz": "Тауықтың төс еті, ірімшік пен кілегей тұздығы және гарнир",
    "composition_en": "Chicken breast, creamy cheese sauce and a side",
    "source_article": "00023"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00021-88",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Картофель по-домашнему с мясом",
    "name_kz": "Ет қосылған үй стиліндегі картоп",
    "name_en": "Homestyle Potatoes with Meat",
    "price": 3990,
    "weight": "380g",
    "composition_ru": "Картофель, мясо, репчатый лук, чеснок и зелень",
    "composition_kz": "Картоп, ет, пияз, сарымсақ және көк шөптер",
    "composition_en": "Potatoes, meat, onions, garlic and fresh herbs",
    "source_article": "00021"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00004-93",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Куырдак",
    "name_kz": "Қуырдақ",
    "name_en": "Kuyrdak",
    "price": 4090,
    "weight": "400g",
    "composition_ru": "Мясо, картофель, лук и традиционные специи",
    "composition_kz": "Ет, картоп, пияз және дәстүрлі дәмдеуіштер",
    "composition_en": "Meat, potatoes, onions and traditional spices",
    "source_article": "00004"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00024-90",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Колбаски из говядины",
    "name_kz": "Сиыр етінен жасалған шұжықтар",
    "name_en": "Beef Sausages",
    "price": 3390,
    "weight": "350g",
    "composition_ru": "Колбаски из говядины с гарниром и соусом",
    "composition_kz": "Гарнир және тұздық қосылған сиыр етінің шұжықтары",
    "composition_en": "Beef sausages with a side and sauce",
    "source_article": "00024"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00025-91",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Колбаски куриные",
    "name_kz": "Тауық шұжықтары",
    "name_en": "Chicken Sausages",
    "price": 2990,
    "weight": "350g",
    "composition_ru": "Куриные колбаски, гарнир и соус",
    "composition_kz": "Тауық шұжықтары, гарнир және соус",
    "composition_en": "Chicken sausages served with a side and sauce",
    "source_article": "00025"
  },
  {
    "category_ru": "Основные блюда",
    "category_kz": "Негізгі тағамдар",
    "category_en": "Main Courses",
    "id": "k-00026-89",
    "type": "kitchen",
    "category_id": "mains",
    "name_ru": "Колбаски из баранины",
    "name_kz": "Қой етінен жасалған шұжықтар",
    "name_en": "Lamb Sausages",
    "price": 3390,
    "weight": "350g",
    "composition_ru": "Колбаски из баранины с гарниром и соусом",
    "composition_kz": "Гарнир және тұздық қосылған қой етінің шұжықтары",
    "composition_en": "Lamb sausages with a side and sauce",
    "source_article": "00026"
  },
  {
    "category_ru": "Паста",
    "category_kz": "Паста",
    "category_en": "Pasta",
    "id": "k-00028-111",
    "type": "kitchen",
    "category_id": "pasta",
    "name_ru": "Фарфалле с морепродуктами",
    "name_kz": "Теңіз өнімдері қосылған фарфалле",
    "name_en": "Seafood Farfalle",
    "price": 4990,
    "weight": "300g",
    "composition_ru": "Фарфалле, креветки, мидии, кальмары, сливочный соус, чеснок и зелень",
    "composition_kz": "Фарфалле, асшаян, мидия, кальмар, кілегейлі соус, сарымсақ және көк шөптер",
    "composition_en": "Farfalle, shrimp, mussels, calamari, cream sauce, garlic and herbs",
    "source_article": "00028"
  },
  {
    "category_ru": "Паста",
    "category_kz": "Паста",
    "category_en": "Pasta",
    "id": "k-00027-112",
    "type": "kitchen",
    "category_id": "pasta",
    "name_ru": "Фетучини с курицей и грибами",
    "name_kz": "Тауық еті мен саңырауқұлақ қосылған фетучини",
    "name_en": "Fettuccine with Chicken & Mushrooms",
    "price": 2990,
    "weight": "300g",
    "composition_ru": "Фетучини, куриное филе, шампиньоны, сливочный соус и пармезан",
    "composition_kz": "Фетучини, тауық филесі, шампиньон, кілегейлі соус және пармезан",
    "composition_en": "Fettuccine, chicken fillet, mushrooms, cream sauce and Parmesan",
    "source_article": "00027"
  },
  {
    "category_ru": "Паста",
    "category_kz": "Паста",
    "category_en": "Pasta",
    "id": "k-00029-110",
    "type": "kitchen",
    "category_id": "pasta",
    "name_ru": "Болоньезе",
    "name_kz": "Болоньезе",
    "name_en": "Bolognese",
    "price": 3290,
    "weight": "300g",
    "composition_ru": "Паста, мясной соус Болоньезе, томаты и пармезан",
    "composition_kz": "Паста, Болоньезе ет соусы, қызанақ және пармезан",
    "composition_en": "Pasta with Bolognese meat sauce, tomatoes and Parmesan",
    "source_article": "00029"
  },
  {
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және пісірмелер",
    "category_en": "Pizza & Bakery",
    "id": "k-00053-118",
    "type": "kitchen",
    "category_id": "pizza_bakery",
    "name_ru": "Пицца с курицей и грибами",
    "name_kz": "Тауық еті мен саңырауқұлақ қосылған пицца",
    "name_en": "Chicken & Mushroom Pizza",
    "price": 3090,
    "weight": "550g",
    "composition_ru": "Томатный соус, моцарелла, куриное филе, шампиньоны и зелень",
    "composition_kz": "Қызанақ соусы, моцарелла, тауық филесі, шампиньон және көк шөптер",
    "composition_en": "Tomato sauce, mozzarella, chicken fillet, mushrooms and herbs",
    "source_article": "00053"
  },
  {
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және пісірмелер",
    "category_en": "Pizza & Bakery",
    "id": "k-00055-116",
    "type": "kitchen",
    "category_id": "pizza_bakery",
    "name_ru": "Мексиканская пицца с халапеньо",
    "name_kz": "Халапеньо қосылған мексикалық пицца",
    "name_en": "Mexican Jalapeño Pizza",
    "price": 3590,
    "weight": "550g",
    "composition_ru": "Томатный соус, моцарелла, мясная начинка, сладкий перец, кукуруза и халапеньо",
    "composition_kz": "Қызанақ соусы, моцарелла, ет салмасы, тәтті бұрыш, жүгері және халапеньо",
    "composition_en": "Tomato sauce, mozzarella, seasoned meat, sweet peppers, corn and jalapeño",
    "source_article": "00055",
    "note": "Острое блюдо"
  },
  {
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және пісірмелер",
    "category_en": "Pizza & Bakery",
    "id": "k-00051-117",
    "type": "kitchen",
    "category_id": "pizza_bakery",
    "name_ru": "Пицца Пепперони",
    "name_kz": "Пепперони пиццасы",
    "name_en": "Pepperoni Pizza",
    "price": 3090,
    "weight": "550g",
    "composition_ru": "Томатный соус, моцарелла и пепперони",
    "composition_kz": "Қызанақ соусы, моцарелла және пепперони",
    "composition_en": "Tomato sauce, mozzarella and pepperoni",
    "source_article": "00051"
  },
  {
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және пісірмелер",
    "category_en": "Pizza & Bakery",
    "id": "k-00052-115",
    "type": "kitchen",
    "category_id": "pizza_bakery",
    "name_ru": "Пицца Маргарита",
    "name_kz": "Маргарита пиццасы",
    "name_en": "Margherita Pizza",
    "price": 2590,
    "weight": "500g",
    "composition_ru": "Томатный соус, моцарелла, томаты и базилик",
    "composition_kz": "Қызанақ соусы, моцарелла, қызанақ және базилик",
    "composition_en": "Tomato sauce, mozzarella, tomatoes and basil",
    "source_article": "00052"
  },
  {
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және пісірмелер",
    "category_en": "Pizza & Bakery",
    "id": "k-00054-114",
    "type": "kitchen",
    "category_id": "pizza_bakery",
    "name_ru": "Пицца Болоньезе",
    "name_kz": "Болоньезе пиццасы",
    "name_en": "Bolognese Pizza",
    "price": 2990,
    "weight": "520g",
    "composition_ru": "Томатный соус, моцарелла, мясной соус Болоньезе и зелень",
    "composition_kz": "Қызанақ соусы, моцарелла, Болоньезе ет соусы және көк шөптер",
    "composition_en": "Tomato sauce, mozzarella, Bolognese meat sauce and herbs",
    "source_article": "00054"
  },
  {
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және пісірмелер",
    "category_en": "Pizza & Bakery",
    "id": "k-00129-119",
    "type": "kitchen",
    "category_id": "pizza_bakery",
    "name_ru": "Хачапури по-мегрельски",
    "name_kz": "Мегрелше хачапури",
    "name_en": "Megrelian Khachapuri",
    "price": 2790,
    "weight": "500g",
    "composition_ru": "Дрожжевое тесто и сырная начинка с запечённым сыром сверху",
    "composition_kz": "Ашытқылы қамыр, ірімшік салмасы және үстіне пісірілген ірімшік",
    "composition_en": "Yeast dough with a cheese filling and an extra layer of baked cheese on top",
    "source_article": "00129"
  },
  {
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және пісірмелер",
    "category_en": "Pizza & Bakery",
    "id": "k-00090-113",
    "type": "kitchen",
    "category_id": "pizza_bakery",
    "name_ru": "Лепёшка",
    "name_kz": "Табан нан",
    "name_en": "Flatbread",
    "price": 590,
    "weight": "180g",
    "composition_ru": "Свежая лепёшка из пшеничного теста",
    "composition_kz": "Бидай қамырынан пісірілген балғын таба нан",
    "composition_en": "Freshly baked wheat flatbread",
    "source_article": "00090"
  },
  {
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және пісірмелер",
    "category_en": "Pizza & Bakery",
    "id": "k-00089-120",
    "type": "kitchen",
    "category_id": "pizza_bakery",
    "name_ru": "Хлебная корзина",
    "name_kz": "Нан себеті",
    "name_en": "Bread Basket",
    "price": 890,
    "weight": "250g",
    "composition_ru": "Ассорти свежего хлеба",
    "composition_kz": "Балғын нан ассортиі",
    "composition_en": "Assorted fresh bread",
    "source_article": "00089"
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-00082-149",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Антрекот на мангале",
    "name_kz": "Мангалдағы антрекот",
    "name_en": "Charcoal-Grilled Entrecôte",
    "price": 3490,
    "weight": "300g",
    "composition_ru": "Антрекот, лаваш и маринованный лук",
    "composition_kz": "Антрекот, лаваш және маринадталған пияз",
    "composition_en": "Entrecôte, lavash and pickled onion",
    "source_article": "00082",
    "featured": true
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-excel-row-218-158",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Бараньи семечки",
    "name_kz": "Қой қабырғалары",
    "name_en": "Grilled Lamb Ribs",
    "price": 2490,
    "composition_ru": "Бараньи рёбрышки, лаваш и маринованный лук",
    "composition_kz": "Қой қабырғалары, лаваш және маринадталған пияз",
    "composition_en": "Lamb ribs, lavash and pickled onion",
    "source_article": "excel-row-218",
    "weight": ""
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-00081-150",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Шашлык из баранины",
    "name_kz": "Қой етінен кәуап",
    "name_en": "Lamb Shashlik",
    "price": 2490,
    "weight": "250g",
    "composition_ru": "Маринованная баранина, лаваш и лук",
    "composition_kz": "Маринадталған қой еті, лаваш және пияз",
    "composition_en": "Marinated lamb, lavash and onion",
    "source_article": "00081"
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-00077-151",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Шашлык из куриных крыльев",
    "name_kz": "Тауық қанаттарынан кәуап",
    "name_en": "Chicken Wing Shashlik",
    "price": 2190,
    "weight": "300g",
    "composition_ru": "Маринованные куриные крылья, лаваш и лук",
    "composition_kz": "Маринадталған тауық қанаттары, лаваш және пияз",
    "composition_en": "Marinated chicken wings, lavash and onion",
    "source_article": "00077"
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-00079-152",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Шашлык из куриного филе",
    "name_kz": "Тауық филесінен кәуап",
    "name_en": "Chicken Fillet Shashlik",
    "price": 2190,
    "weight": "250g",
    "composition_ru": "Маринованное куриное филе, лаваш и лук",
    "composition_kz": "Маринадталған тауық филесі, лаваш және пияз",
    "composition_en": "Marinated chicken fillet, lavash and onion",
    "source_article": "00079"
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-00076-153",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Шашлык из куриного окорочка",
    "name_kz": "Тауық санының кәуабы",
    "name_en": "Chicken Thigh Shashlik",
    "price": 2190,
    "weight": "320g",
    "composition_ru": "Маринованное куриное бедро, лаваш и лук",
    "composition_kz": "Маринадталған тауық саны, лаваш және пияз",
    "composition_en": "Marinated chicken thigh, lavash and onion",
    "source_article": "00076"
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-00078-154",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Шашлык из утки",
    "name_kz": "Үйрек етінен кәуап",
    "name_en": "Duck Shashlik",
    "price": 2190,
    "weight": "250g",
    "composition_ru": "Маринованное мясо утки, лаваш и лук",
    "composition_kz": "Маринадталған үйрек еті, лаваш және пияз",
    "composition_en": "Marinated duck, lavash and onion",
    "source_article": "00078"
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-00080-155",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Люля-кебаб",
    "name_kz": "Люля-кебаб",
    "name_en": "Lula Kebab",
    "price": 2190,
    "weight": "250g",
    "composition_ru": "Рубленое мясо, лаваш и маринованный лук",
    "composition_kz": "Тартылған ет, лаваш және маринадталған пияз",
    "composition_en": "Minced meat, lavash and pickled onion",
    "source_article": "00080"
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-00084-156",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Овощи на мангале",
    "name_kz": "Мангалдағы көкөністер",
    "name_en": "Charcoal-Grilled Vegetables",
    "price": 1690,
    "weight": "250g",
    "composition_ru": "Сезонные овощи, приготовленные на мангале",
    "composition_kz": "Мангалда дайындалған маусымдық көкөністер",
    "composition_en": "Seasonal vegetables cooked over charcoal",
    "source_article": "00084"
  },
  {
    "category_ru": "Мангал",
    "category_kz": "Мангал",
    "category_en": "Charcoal Grill",
    "id": "k-00083-157",
    "type": "kitchen",
    "category_id": "grill",
    "name_ru": "Шампиньоны на мангале",
    "name_kz": "Мангалдағы қозықұйрықтар",
    "name_en": "Charcoal-Grilled Mushrooms",
    "price": 1690,
    "weight": "200g",
    "composition_ru": "Шампиньоны, красный соус и лаваш",
    "composition_kz": "Қозықұйрықтар, қызыл тұздық және лаваш",
    "composition_en": "Mushrooms, red sauce and lavash",
    "source_article": "00083"
  },
  {
    "category_ru": "Закуски к пиву",
    "category_kz": "Сыраға арналған тіскебасарлар",
    "category_en": "Beer Snacks",
    "id": "k-00126-105",
    "type": "kitchen",
    "category_id": "beer_snacks",
    "name_ru": "Большой сет закусок",
    "name_kz": "Үлкен тіскебасар сеті",
    "name_en": "Large Snack Platter",
    "price": 6990,
    "weight": "850g",
    "composition_ru": "Креветки, чесночные гренки, копчёный чечил, картофель фри, сосиски и луковые кольца",
    "composition_kz": "Асшаян, сарымсақты гренки, ысталған чечил, фри, шұжық және пияз сақиналары",
    "composition_en": "Shrimp, garlic croutons, smoked Chechil cheese, fries, sausages and onion rings",
    "source_article": "00126"
  },
  {
    "category_ru": "Закуски к пиву",
    "category_kz": "Сыраға арналған тіскебасарлар",
    "category_en": "Beer Snacks",
    "id": "k-00067-106",
    "type": "kitchen",
    "category_id": "beer_snacks",
    "name_ru": "Креветки пивные",
    "name_kz": "Дәмдеуішті асшаяндар",
    "name_en": "Spiced Shrimp",
    "price": 3990,
    "weight": "300g",
    "composition_ru": "Обжаренные креветки с чесноком, специями, лимоном и зеленью",
    "composition_kz": "Сарымсақ, дәмдеуіштер, лимон және көк шөптермен қуырылған асшаяндар",
    "composition_en": "Pan-fried shrimp with garlic, spices, lemon and fresh herbs",
    "source_article": "00067"
  },
  {
    "category_ru": "Закуски к пиву",
    "category_kz": "Сыраға арналған тіскебасарлар",
    "category_en": "Beer Snacks",
    "id": "k-00066-109",
    "type": "kitchen",
    "category_id": "beer_snacks",
    "name_ru": "Чечил копченый",
    "name_kz": "Ысталған чечил",
    "name_en": "Smoked Chechil Cheese",
    "price": 1390,
    "weight": "100g",
    "composition_ru": "Копчёный рассольный сыр чечил",
    "composition_kz": "Ысталған тұзды чечил ірімшігі",
    "composition_en": "Smoked brined Chechil string cheese",
    "source_article": "00066"
  },
  {
    "category_ru": "Закуски к пиву",
    "category_kz": "Сыраға арналған тіскебасарлар",
    "category_en": "Beer Snacks",
    "id": "k-00069-108",
    "type": "kitchen",
    "category_id": "beer_snacks",
    "name_ru": "Чесночные гренки",
    "name_kz": "Сарымсақты гренки",
    "name_en": "Garlic Croutons",
    "price": 1590,
    "weight": "180g",
    "composition_ru": "Ржаные гренки с чесноком и фирменным соусом",
    "composition_kz": "Сарымсақ қосылған қара нан гренкиі және фирмалық соус",
    "composition_en": "Rye bread croutons with garlic and house sauce",
    "source_article": "00069"
  },
  {
    "category_ru": "Закуски к пиву",
    "category_kz": "Сыраға арналған тіскебасарлар",
    "category_en": "Beer Snacks",
    "id": "k-00068-107",
    "type": "kitchen",
    "category_id": "beer_snacks",
    "name_ru": "Фисташки",
    "name_kz": "Пісте",
    "name_en": "Pistachios",
    "price": 1590,
    "weight": "100g",
    "composition_ru": "Обжаренные солёные фисташки",
    "composition_kz": "Қуырылған тұзды пісте",
    "composition_en": "Roasted salted pistachios",
    "source_article": "00068"
  },
  {
    "category_ru": "Закуски к пиву",
    "category_kz": "Сыраға арналған тіскебасарлар",
    "category_en": "Beer Snacks",
    "id": "k-00127-104",
    "type": "kitchen",
    "category_id": "beer_snacks",
    "name_ru": "Арахис",
    "name_kz": "Жержаңғақ",
    "name_en": "Peanuts",
    "price": 1390,
    "weight": "120g",
    "composition_ru": "Обжаренный солёный арахис",
    "composition_kz": "Қуырылған тұзды жержаңғақ",
    "composition_en": "Roasted salted peanuts",
    "source_article": "00127"
  },
  {
    "category_ru": "Для компании",
    "category_kz": "Компанияға арналған",
    "category_en": "For Sharing",
    "id": "k-00103-128",
    "type": "kitchen",
    "category_id": "sharing",
    "name_ru": "Куырдак на компанию",
    "name_kz": "Компанияға арналған қуырдақ",
    "name_en": "Kuyrdak for Sharing",
    "price": 20450,
    "composition_ru": "Мясо, картофель, лук",
    "composition_kz": "Ет, картоп, пияз",
    "composition_en": "Meat, potatoes and onions",
    "source_article": "00103",
    "weight": "3200g"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00074-81",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Овощи гриль",
    "name_kz": "Гриль көкөністері",
    "name_en": "Grilled Vegetables",
    "price": 1990,
    "weight": "250g",
    "composition_ru": "Баклажан, кабачок, сладкий перец, томаты и шампиньоны",
    "composition_kz": "Баялды, кәді, тәтті бұрыш, қызанақ және шампиньон",
    "composition_en": "Eggplant, zucchini, sweet peppers, tomatoes and mushrooms",
    "source_article": "00074"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00070-78",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Картофель фри",
    "name_kz": "Картоп фри",
    "name_en": "French Fries",
    "price": 1190,
    "weight": "150g",
    "composition_ru": "Хрустящий картофель фри",
    "composition_kz": "Қытырлақ картоп фри",
    "composition_en": "Crispy French fries",
    "source_article": "00070"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00071-80",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Картофельные дольки",
    "name_kz": "Картоп тілімдері",
    "name_en": "Potato Wedges",
    "price": 1390,
    "weight": "200g",
    "composition_ru": "Запечённые картофельные дольки со специями",
    "composition_kz": "Дәмдеуіштермен пісірілген картоп тілімдері",
    "composition_en": "Seasoned baked potato wedges",
    "source_article": "00071"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00073-79",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Картофельное пюре",
    "name_kz": "Картоп езбесі",
    "name_en": "Mashed Potatoes",
    "price": 790,
    "composition_ru": "Картофель, сливочное масло и молоко",
    "composition_kz": "Картоп, сары май және сүт",
    "composition_en": "Potatoes, butter and milk",
    "source_article": "00073",
    "weight": "200g"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00072-82",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Рис",
    "name_kz": "Күріш",
    "name_en": "Rice",
    "price": 790,
    "weight": "150g",
    "composition_ru": "Отварной рис",
    "composition_kz": "Пісірілген күріш",
    "composition_en": "Steamed rice",
    "source_article": "00072"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00088-133",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Соус тартар",
    "name_kz": "Тартар тұздығы",
    "name_en": "Tartar Sauce",
    "price": 590,
    "weight": "50g",
    "composition_ru": "Сливочный соус с маринованным огурцом и зеленью",
    "composition_kz": "Маринадталған қияр мен көк шөп қосылған кілегейлі тұздық",
    "composition_en": "Creamy sauce with pickles and herbs",
    "source_article": "00088"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00085-132",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Сырный соус",
    "name_kz": "Ірімшік тұздығы",
    "name_en": "Cheese Sauce",
    "price": 590,
    "weight": "50g",
    "composition_ru": "Сливочный сырный соус",
    "composition_kz": "Кілегейлі ірімшік тұздығы",
    "composition_en": "Creamy cheese sauce",
    "source_article": "00085"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00086-131",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Красный соус",
    "name_kz": "Қызыл тұздық",
    "name_en": "Red Sauce",
    "price": 590,
    "weight": "50g",
    "composition_ru": "Томатный соус со специями",
    "composition_kz": "Дәмдеуіштер қосылған қызанақ тұздығы",
    "composition_en": "Tomato sauce with spices",
    "source_article": "00086"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00133-130",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Белый соус",
    "name_kz": "Ақ тұздық",
    "name_en": "White Sauce",
    "price": 590,
    "weight": "50g",
    "composition_ru": "Сливочный соус с чесноком и зеленью",
    "composition_kz": "Сарымсақ пен көк шөп қосылған кілегейлі тұздық",
    "composition_en": "Creamy sauce with garlic and herbs",
    "source_article": "00133"
  },
  {
    "category_ru": "Гарниры и соусы",
    "category_kz": "Гарнирлер мен тұздықтар",
    "category_en": "Sides & Sauces",
    "id": "k-00087-129",
    "type": "kitchen",
    "category_id": "sides_sauces",
    "name_ru": "Кетчуп",
    "name_kz": "Кетчуп",
    "name_en": "Ketchup",
    "price": 590,
    "weight": "50g",
    "composition_ru": "Классический томатный кетчуп",
    "composition_kz": "Классикалық қызанақ кетчупы",
    "composition_en": "Classic tomato ketchup",
    "source_article": "00087"
  },
  {
    "category_ru": "Десерты и фрукты",
    "category_kz": "Десерттер мен жемістер",
    "category_en": "Desserts & Fruit",
    "id": "k-00095-100",
    "type": "kitchen",
    "category_id": "desserts_fruit",
    "name_ru": "Восточные сладости",
    "name_kz": "Шығыс тәттілері",
    "name_en": "Oriental Sweets Platter",
    "price": 5490,
    "weight": "450g",
    "composition_ru": "Ассорти восточных сладостей, орехов и сухофруктов",
    "composition_kz": "Шығыс тәттілері, жаңғақтар және кептірілген жемістер ассортиі",
    "composition_en": "Assorted oriental sweets, nuts and dried fruits",
    "source_article": "00095"
  },
  {
    "category_ru": "Десерты и фрукты",
    "category_kz": "Десерттер мен жемістер",
    "category_en": "Desserts & Fruit",
    "id": "k-00101-102",
    "type": "kitchen",
    "category_id": "desserts_fruit",
    "name_ru": "Фруктовая ваза",
    "name_kz": "Жеміс табағы",
    "name_en": "Fruit Platter",
    "price": 7490,
    "composition_ru": "Сезонные фрукты и ягоды",
    "composition_kz": "Маусымдық жемістер мен жидектер",
    "composition_en": "Seasonal fruit and berries",
    "source_article": "00101",
    "weight": ""
  },
  {
    "category_ru": "Десерты и фрукты",
    "category_kz": "Десерттер мен жемістер",
    "category_en": "Desserts & Fruit",
    "id": "k-00094-101",
    "type": "kitchen",
    "category_id": "desserts_fruit",
    "name_ru": "Пирожные в ассортименте",
    "name_kz": "Ассорти тәттілер",
    "name_en": "Assorted Pastries",
    "price": 1990,
    "weight": "150g",
    "composition_ru": "Ассорти десертов",
    "composition_kz": "Десерттер ассортиі",
    "composition_en": "A selection of desserts",
    "source_article": "00094"
  },
  {
    "category_ru": "Десерты и фрукты",
    "category_kz": "Десерттер мен жемістер",
    "category_en": "Desserts & Fruit",
    "id": "k-00112-99",
    "type": "kitchen",
    "category_id": "desserts_fruit",
    "name_ru": "Арбуз и дыня",
    "name_kz": "Қарбыз бен қауын",
    "name_en": "Watermelon & Melon",
    "price": 1490,
    "composition_ru": "Свежие арбуз и дыня",
    "composition_kz": "Балғын қарбыз бен қауын",
    "composition_en": "Fresh watermelon and melon",
    "source_article": "00112",
    "weight": ""
  },
  {
    "category_ru": "Белое по бокалам",
    "category_kz": "Бокалмен ақ шарап",
    "category_en": "White Wine by the Glass",
    "id": "b-00414-6",
    "type": "bar",
    "category_id": "white_wine_glass",
    "name_ru": "Pinot Grigio. Inycon",
    "name_kz": "Pinot Grigio. Inycon",
    "name_en": "Pinot Grigio. Inycon",
    "price": 1990,
    "weight": "150ml",
    "composition_ru": "Белое вино, сухое",
    "composition_kz": "Ақ шарап, құрғақ",
    "composition_en": "White wine, dry",
    "source_article": "00414"
  },
  {
    "category_ru": "Белое по бокалам",
    "category_kz": "Бокалмен ақ шарап",
    "category_en": "White Wine by the Glass",
    "id": "b-00413-2",
    "type": "bar",
    "category_id": "white_wine_glass",
    "name_ru": "Moscato. Roche Mazet",
    "name_kz": "Moscato. Roche Mazet",
    "name_en": "Moscato. Roche Mazet",
    "price": 1990,
    "weight": "150ml",
    "composition_ru": "Белое вино, полусладкое",
    "composition_kz": "Ақ шарап, жартылай тәтті",
    "composition_en": "White wine, semi-sweet",
    "source_article": "00413"
  },
  {
    "category_ru": "Красное по бокалам",
    "category_kz": "Бокалмен қызыл шарап",
    "category_en": "Red Wine by the Glass",
    "id": "b-00417-5",
    "type": "bar",
    "category_id": "red_wine_glass",
    "name_ru": "Nero d'Avola. Inycon",
    "name_kz": "Nero d'Avola. Inycon",
    "name_en": "Nero d'Avola. Inycon",
    "price": 1990,
    "weight": "150ml",
    "composition_ru": "Красное вино, сухое",
    "composition_kz": "Қызыл шарап, құрғақ",
    "composition_en": "Red wine, dry",
    "source_article": "00417"
  },
  {
    "category_ru": "Красное по бокалам",
    "category_kz": "Бокалмен қызыл шарап",
    "category_en": "Red Wine by the Glass",
    "id": "b-00416-1",
    "type": "bar",
    "category_id": "red_wine_glass",
    "name_ru": "Grenache. Roche Mazet",
    "name_kz": "Grenache. Roche Mazet",
    "name_en": "Grenache. Roche Mazet",
    "price": 1990,
    "weight": "150ml",
    "composition_ru": "Красное вино, полусладкое",
    "composition_kz": "Қызыл шарап, жартылай тәтті",
    "composition_en": "Red wine, semi-sweet",
    "source_article": "00416"
  },
  {
    "category_ru": "Розовое по бокалам",
    "category_kz": "Бокалмен қызғылт шарап",
    "category_en": "Rosé Wine by the Glass",
    "id": "b-00415-8",
    "type": "bar",
    "category_id": "rose_wine_glass",
    "name_ru": "Zinfandel Rose. Beringer",
    "name_kz": "Zinfandel Rose. Beringer",
    "name_en": "Zinfandel Rose. Beringer",
    "price": 2290,
    "weight": "150ml",
    "composition_ru": "Розовое вино, полусладкое",
    "composition_kz": "Қызғылт шарап, жартылай тәтті",
    "composition_en": "Rosé wine, semi-sweet",
    "source_article": "00415"
  },
  {
    "category_ru": "Безалкогольное вино",
    "category_kz": "Алкогольсіз шарап",
    "category_en": "Non-Alcoholic Wine",
    "id": "b-00407-7",
    "type": "bar",
    "category_id": "nonalcoholic_wine",
    "name_ru": "Zero Sparkling. Codorniu",
    "name_kz": "Zero Sparkling. Codorniu",
    "name_en": "Zero Sparkling. Codorniu",
    "price": 2490,
    "weight": "150ml",
    "composition_ru": "Безалкогольное белое игристое вино",
    "composition_kz": "Алкогольсіз ақ көпіршікті шарап",
    "composition_en": "Non-alcoholic white sparkling wine",
    "source_article": "00407"
  },
  {
    "category_ru": "Безалкогольное вино",
    "category_kz": "Алкогольсіз шарап",
    "category_en": "Non-Alcoholic Wine",
    "id": "b-00408-4",
    "type": "bar",
    "category_id": "nonalcoholic_wine",
    "name_ru": "Natureo Muscat. Torres",
    "name_kz": "Natureo Muscat. Torres",
    "name_en": "Natureo Muscat. Torres",
    "price": 2490,
    "weight": "150ml",
    "composition_ru": "Безалкогольное белое вино, полусладкое",
    "composition_kz": "Алкогольсіз ақ шарап, жартылай тәтті",
    "composition_en": "Non-alcoholic white wine, semi-sweet",
    "source_article": "00408"
  },
  {
    "category_ru": "Безалкогольное вино",
    "category_kz": "Алкогольсіз шарап",
    "category_en": "Non-Alcoholic Wine",
    "id": "b-00409-3",
    "type": "bar",
    "category_id": "nonalcoholic_wine",
    "name_ru": "Natureo Garnacha Syrah. Torres",
    "name_kz": "Natureo Garnacha Syrah. Torres",
    "name_en": "Natureo Garnacha Syrah. Torres",
    "price": 2490,
    "weight": "150ml",
    "composition_ru": "Безалкогольное красное вино, сухое",
    "composition_kz": "Алкогольсіз қызыл шарап, құрғақ",
    "composition_en": "Non-alcoholic red wine, dry",
    "source_article": "00409"
  },
  {
    "category_ru": "Игристое вино",
    "category_kz": "Көпіршікті шарап",
    "category_en": "Sparkling Wine",
    "id": "b-00418-14",
    "type": "bar",
    "category_id": "sparkling_wine",
    "name_ru": "Prosecco di Valdobbiadene Extra Dry. Giall'Oro. Ruggeri",
    "name_kz": "Prosecco di Valdobbiadene Extra Dry. Giall'Oro. Ruggeri",
    "name_en": "Prosecco di Valdobbiadene Extra Dry. Giall'Oro. Ruggeri",
    "price": 17990,
    "weight": "750ml",
    "composition_ru": "Розовое игристое вино, экстра-сухое",
    "composition_kz": "Қызғылт көпіршікті шарап, экстра-құрғақ",
    "composition_en": "Rosé sparkling wine, extra dry",
    "source_article": "00418"
  },
  {
    "category_ru": "Игристое вино",
    "category_kz": "Көпіршікті шарап",
    "category_en": "Sparkling Wine",
    "id": "b-00419-9",
    "type": "bar",
    "category_id": "sparkling_wine",
    "name_ru": "Asti. Cinzano",
    "name_kz": "Asti. Cinzano",
    "name_en": "Asti. Cinzano",
    "price": 15990,
    "weight": "750ml",
    "composition_ru": "Белое игристое вино, сладкое",
    "composition_kz": "Ақ көпіршікті шарап, тәтті",
    "composition_en": "White sparkling wine, sweet",
    "source_article": "00419"
  },
  {
    "category_ru": "Игристое вино",
    "category_kz": "Көпіршікті шарап",
    "category_en": "Sparkling Wine",
    "id": "b-00123-21",
    "type": "bar",
    "category_id": "sparkling_wine",
    "name_ru": "Blanc de Blancs Tete de Cheval",
    "name_kz": "Blanc de Blancs Tete de Cheval",
    "name_en": "Blanc de Blancs Tete de Cheval",
    "price": 14990,
    "weight": "750ml",
    "composition_ru": "Белое игристое вино",
    "composition_kz": "Ақ көпіршікті шарап",
    "composition_en": "White sparkling wine",
    "source_article": "00123"
  },
  {
    "category_ru": "Игристое вино",
    "category_kz": "Көпіршікті шарап",
    "category_en": "Sparkling Wine",
    "id": "b-00412-15",
    "type": "bar",
    "category_id": "sparkling_wine",
    "name_ru": "Prosecco Dry. Cinzano",
    "name_kz": "Prosecco Dry. Cinzano",
    "name_en": "Prosecco Dry. Cinzano",
    "price": 11990,
    "weight": "750ml",
    "composition_ru": "Розовое игристое вино, сухое",
    "composition_kz": "Қызғылт көпіршікті шарап, құрғақ",
    "composition_en": "Rosé sparkling wine, dry",
    "source_article": "00412"
  },
  {
    "category_ru": "Игристое вино",
    "category_kz": "Көпіршікті шарап",
    "category_en": "Sparkling Wine",
    "id": "b-00105-50",
    "type": "bar",
    "category_id": "sparkling_wine",
    "name_ru": "Roger d'Anoia",
    "name_kz": "Roger d'Anoia",
    "name_en": "Roger d'Anoia",
    "price": 8990,
    "weight": "750ml",
    "composition_ru": "Белое игристое вино, сухое",
    "composition_kz": "Ақ көпіршікті шарап, құрғақ",
    "composition_en": "White sparkling wine, dry",
    "source_article": "00105"
  },
  {
    "category_ru": "Игристое вино",
    "category_kz": "Көпіршікті шарап",
    "category_en": "Sparkling Wine",
    "id": "b-00410-13",
    "type": "bar",
    "category_id": "sparkling_wine",
    "name_ru": "Prosecco Brut. Argeo. Ruggeri",
    "name_kz": "Prosecco Brut. Argeo. Ruggeri",
    "name_en": "Prosecco Brut. Argeo. Ruggeri",
    "price": 4990,
    "weight": "200ml",
    "composition_ru": "Розовое игристое вино, сухое",
    "composition_kz": "Қызғылт көпіршікті шарап, құрғақ",
    "composition_en": "Rosé sparkling wine, dry",
    "source_article": "00410"
  },
  {
    "category_ru": "Игристое вино",
    "category_kz": "Көпіршікті шарап",
    "category_en": "Sparkling Wine",
    "id": "b-00411-16",
    "type": "bar",
    "category_id": "sparkling_wine",
    "name_ru": "Prosecco Rose Brut. Argeo. Ruggeri",
    "name_kz": "Prosecco Rose Brut. Argeo. Ruggeri",
    "name_en": "Prosecco Rose Brut. Argeo. Ruggeri",
    "price": 4990,
    "weight": "200ml",
    "composition_ru": "Розовое игристое вино, сухое",
    "composition_kz": "Қызғылт көпіршікті шарап, құрғақ",
    "composition_en": "Rosé sparkling wine, dry",
    "source_article": "00411"
  },
  {
    "category_ru": "Белое вино",
    "category_kz": "Ақ шарап",
    "category_en": "White Wine",
    "id": "b-00423-18",
    "type": "bar",
    "category_id": "white_wine",
    "name_ru": "Sauvignon Blanc. Nuala",
    "name_kz": "Sauvignon Blanc. Nuala",
    "name_en": "Sauvignon Blanc. Nuala",
    "price": 19990,
    "weight": "750ml",
    "composition_ru": "Белое вино, сухое",
    "composition_kz": "Ақ шарап, құрғақ",
    "composition_en": "White wine, dry",
    "source_article": "00423"
  },
  {
    "category_ru": "Белое вино",
    "category_kz": "Ақ шарап",
    "category_en": "White Wine",
    "id": "b-00421-20",
    "type": "bar",
    "category_id": "white_wine",
    "name_ru": "Vermentino. Timo. Bianco Salento. Cantine San Marzano",
    "name_kz": "Vermentino. Timo. Bianco Salento. Cantine San Marzano",
    "name_en": "Vermentino. Timo. Bianco Salento. Cantine San Marzano",
    "price": 14990,
    "weight": "750ml",
    "composition_ru": "Белое вино, сухое",
    "composition_kz": "Ақ шарап, құрғақ",
    "composition_en": "White wine, dry",
    "source_article": "00421"
  },
  {
    "category_ru": "Белое вино",
    "category_kz": "Ақ шарап",
    "category_en": "White Wine",
    "id": "b-00422-17",
    "type": "bar",
    "category_id": "white_wine",
    "name_ru": "San Valentin. Torres",
    "name_kz": "San Valentin. Torres",
    "name_en": "San Valentin. Torres",
    "price": 14990,
    "weight": "750ml",
    "composition_ru": "Испания · Парельяда",
    "composition_kz": "Испания · Парельяда",
    "composition_en": "Spain · Parellada",
    "source_article": "00422"
  },
  {
    "category_ru": "Белое вино",
    "category_kz": "Ақ шарап",
    "category_en": "White Wine",
    "id": "b-00420-10",
    "type": "bar",
    "category_id": "white_wine",
    "name_ru": "Chardonnay. Le Grand Noir",
    "name_kz": "Chardonnay. Le Grand Noir",
    "name_en": "Chardonnay. Le Grand Noir",
    "price": 12990,
    "weight": "750ml",
    "composition_ru": "Белое вино, сухое",
    "composition_kz": "Ақ шарап, құрғақ",
    "composition_en": "White wine, dry",
    "source_article": "00420"
  },
  {
    "category_ru": "Красное вино",
    "category_kz": "Қызыл шарап",
    "category_en": "Red Wine",
    "id": "b-00425-12",
    "type": "bar",
    "category_id": "red_wine",
    "name_ru": "Primitivo. Il Pumo. Cantine San Marzano",
    "name_kz": "Primitivo. Il Pumo. Cantine San Marzano",
    "name_en": "Primitivo. Il Pumo. Cantine San Marzano",
    "price": 14990,
    "weight": "750ml",
    "composition_ru": "Красное вино, сухое",
    "composition_kz": "Қызыл шарап, құрғақ",
    "composition_en": "Red wine, dry",
    "source_article": "00425"
  },
  {
    "category_ru": "Красное вино",
    "category_kz": "Қызыл шарап",
    "category_en": "Red Wine",
    "id": "b-00424-11",
    "type": "bar",
    "category_id": "red_wine",
    "name_ru": "Pinot Noir. Le Grand Noir",
    "name_kz": "Pinot Noir. Le Grand Noir",
    "name_en": "Pinot Noir. Le Grand Noir",
    "price": 12990,
    "weight": "750ml",
    "composition_ru": "Красное вино, сухое",
    "composition_kz": "Қызыл шарап, құрғақ",
    "composition_en": "Red wine, dry",
    "source_article": "00424"
  },
  {
    "category_ru": "Красное вино",
    "category_kz": "Қызыл шарап",
    "category_en": "Red Wine",
    "id": "b-00426-19",
    "type": "bar",
    "category_id": "red_wine",
    "name_ru": "Shiraz. Barramundi Wines",
    "name_kz": "Shiraz. Barramundi Wines",
    "name_en": "Shiraz. Barramundi Wines",
    "price": 10990,
    "weight": "750ml",
    "composition_ru": "Красное вино, сухое",
    "composition_kz": "Қызыл шарап, құрғақ",
    "composition_en": "Red wine, dry",
    "source_article": "00426"
  },
  {
    "category_ru": "Бутылочное пиво",
    "category_kz": "Бөтелкедегі сыра",
    "category_en": "Bottled Beer",
    "id": "b-00115-36",
    "type": "bar",
    "category_id": "bottled_beer",
    "name_ru": "Ayinger, Brauweisse",
    "name_kz": "Ayinger, Brauweisse",
    "name_en": "Ayinger, Brauweisse",
    "price": 2990,
    "composition_ru": "нефильтрованное",
    "composition_kz": "сүзілмеген",
    "composition_en": "unfiltered",
    "source_article": "00115",
    "weight": "500ml"
  },
  {
    "category_ru": "Бутылочное пиво",
    "category_kz": "Бөтелкедегі сыра",
    "category_en": "Bottled Beer",
    "id": "b-00116-37",
    "type": "bar",
    "category_id": "bottled_beer",
    "name_ru": "Ayinger, Lager",
    "name_kz": "Ayinger, Lager",
    "name_en": "Ayinger, Lager",
    "price": 2990,
    "composition_ru": "фильтрованное",
    "composition_kz": "сүзілген",
    "composition_en": "filtered",
    "source_article": "00116",
    "weight": "500ml"
  },
  {
    "category_ru": "Бутылочное пиво",
    "category_kz": "Бөтелкедегі сыра",
    "category_en": "Bottled Beer",
    "id": "b-00118-38",
    "type": "bar",
    "category_id": "bottled_beer",
    "name_ru": "Gubernija Brown Ale",
    "name_kz": "Gubernija Brown Ale",
    "name_en": "Gubernija Brown Ale",
    "price": 1990,
    "composition_ru": "тёмное",
    "composition_kz": "қара",
    "composition_en": "dark",
    "source_article": "00118",
    "weight": "500ml"
  },
  {
    "category_ru": "Бутылочное пиво",
    "category_kz": "Бөтелкедегі сыра",
    "category_en": "Bottled Beer",
    "id": "b-00117-39",
    "type": "bar",
    "category_id": "bottled_beer",
    "name_ru": "Gubernija Ekstra Lager",
    "name_kz": "Gubernija Ekstra Lager",
    "name_en": "Gubernija Ekstra Lager",
    "price": 1990,
    "composition_ru": "фильтрованное",
    "composition_kz": "сүзілген",
    "composition_en": "filtered",
    "source_article": "00117",
    "weight": "500ml"
  },
  {
    "category_ru": "Разливное пиво",
    "category_kz": "Құймалы сыра",
    "category_en": "Draft Beer",
    "id": "b-00441-40",
    "type": "bar",
    "category_id": "draft_beer",
    "name_ru": "Carlsberg",
    "name_kz": "Carlsberg",
    "name_en": "Carlsberg",
    "price": 2590,
    "composition_ru": "нефильтрованное",
    "composition_kz": "сүзілмеген",
    "composition_en": "unfiltered",
    "source_article": "00441",
    "weight": "500ml"
  },
  {
    "category_ru": "Разливное пиво",
    "category_kz": "Құймалы сыра",
    "category_en": "Draft Beer",
    "id": "b-00113-42",
    "type": "bar",
    "category_id": "draft_beer",
    "name_ru": "Kronenbourg Blanc",
    "name_kz": "Kronenbourg Blanc",
    "name_en": "Kronenbourg Blanc",
    "price": 2290,
    "composition_ru": "нефильтрованное",
    "composition_kz": "сүзілмеген",
    "composition_en": "unfiltered",
    "source_article": "00113",
    "weight": "500ml"
  },
  {
    "category_ru": "Разливное пиво",
    "category_kz": "Құймалы сыра",
    "category_en": "Draft Beer",
    "id": "b-00114-41",
    "type": "bar",
    "category_id": "draft_beer",
    "name_ru": "Holsten Pilsener",
    "name_kz": "Holsten Pilsener",
    "name_en": "Holsten Pilsener",
    "price": 1890,
    "composition_ru": "фильтрованное",
    "composition_kz": "сүзілген",
    "composition_en": "filtered",
    "source_article": "00114",
    "weight": "500ml"
  },
  {
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka",
    "id": "b-00121-23",
    "type": "bar",
    "category_id": "vodka",
    "name_ru": "Mont Blanc",
    "name_kz": "Mont Blanc",
    "name_en": "Mont Blanc",
    "price": 2690,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00121"
  },
  {
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka",
    "id": "b-00120-25",
    "type": "bar",
    "category_id": "vodka",
    "name_ru": "Белуга Нобл",
    "name_kz": "Белуга Нобл",
    "name_en": "Beluga Noble",
    "price": 2690,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00120"
  },
  {
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka",
    "id": "b-00122-22",
    "type": "bar",
    "category_id": "vodka",
    "name_ru": "Koskenkorva",
    "name_kz": "Koskenkorva",
    "name_en": "Koskenkorva",
    "price": 2090,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00122"
  },
  {
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka",
    "id": "b-00097-26",
    "type": "bar",
    "category_id": "vodka",
    "name_ru": "Absolut",
    "name_kz": "Absolut",
    "name_en": "Absolut",
    "price": 1800,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00097"
  },
  {
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka",
    "id": "b-00119-24",
    "type": "bar",
    "category_id": "vodka",
    "name_ru": "Архангельская Северная",
    "name_kz": "Архангельская Северная",
    "name_en": "Arkhangelskaya Severnaya",
    "price": 1790,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00119"
  },
  {
    "category_ru": "Виски",
    "category_kz": "Виски",
    "category_en": "Whisky",
    "id": "b-00430-33",
    "type": "bar",
    "category_id": "whisky",
    "name_ru": "Glenmorangie The Original 12 YO",
    "name_kz": "Glenmorangie The Original 12 YO",
    "name_en": "Glenmorangie The Original 12 YO",
    "price": 2990,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00430"
  },
  {
    "category_ru": "Виски",
    "category_kz": "Виски",
    "category_en": "Whisky",
    "id": "b-00432-32",
    "type": "bar",
    "category_id": "whisky",
    "name_ru": "Bushmills Original",
    "name_kz": "Bushmills Original",
    "name_en": "Bushmills Original",
    "price": 1890,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00432"
  },
  {
    "category_ru": "Виски",
    "category_kz": "Виски",
    "category_en": "Whisky",
    "id": "b-00431-34",
    "type": "bar",
    "category_id": "whisky",
    "name_ru": "Old Smuggler",
    "name_kz": "Old Smuggler",
    "name_en": "Old Smuggler",
    "price": 1490,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00431"
  },
  {
    "category_ru": "Коньяк, бренди и кальвадос",
    "category_kz": "Коньяк, бренди және кальвадос",
    "category_en": "Cognac, Brandy & Calvados",
    "id": "b-00427-35",
    "type": "bar",
    "category_id": "cognac_brandy_calvados",
    "name_ru": "Hennessy VS",
    "name_kz": "Hennessy VS",
    "name_en": "Hennessy VS",
    "price": 2990,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00427"
  },
  {
    "category_ru": "Коньяк, бренди и кальвадос",
    "category_kz": "Коньяк, бренди және кальвадос",
    "category_en": "Cognac, Brandy & Calvados",
    "id": "b-00428-30",
    "type": "bar",
    "category_id": "cognac_brandy_calvados",
    "name_ru": "Calvados Fine. Chateau du Breuil",
    "name_kz": "Calvados Fine. Chateau du Breuil",
    "name_en": "Calvados Fine. Chateau du Breuil",
    "price": 1890,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00428"
  },
  {
    "category_ru": "Коньяк, бренди и кальвадос",
    "category_kz": "Коньяк, бренди және кальвадос",
    "category_en": "Cognac, Brandy & Calvados",
    "id": "b-00429-31",
    "type": "bar",
    "category_id": "cognac_brandy_calvados",
    "name_ru": "Torres 5",
    "name_kz": "Torres 5",
    "name_en": "Torres 5",
    "price": 1290,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00429"
  },
  {
    "category_ru": "Джин",
    "category_kz": "Джин",
    "category_en": "Gin",
    "id": "b-00435-27",
    "type": "bar",
    "category_id": "gin",
    "name_ru": "Citadelle Jardin",
    "name_kz": "Citadelle Jardin",
    "name_en": "Citadelle Jardin",
    "price": 1990,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00435"
  },
  {
    "category_ru": "Джин",
    "category_kz": "Джин",
    "category_en": "Gin",
    "id": "b-00433-28",
    "type": "bar",
    "category_id": "gin",
    "name_ru": "Citadelle Original",
    "name_kz": "Citadelle Original",
    "name_en": "Citadelle Original",
    "price": 1990,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00433"
  },
  {
    "category_ru": "Джин",
    "category_kz": "Джин",
    "category_en": "Gin",
    "id": "b-00434-29",
    "type": "bar",
    "category_id": "gin",
    "name_ru": "Citadelle Rouge",
    "name_kz": "Citadelle Rouge",
    "name_en": "Citadelle Rouge",
    "price": 1990,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00434"
  },
  {
    "category_ru": "Ром",
    "category_kz": "Ром",
    "category_en": "Rum",
    "id": "b-00439-43",
    "type": "bar",
    "category_id": "rum",
    "name_ru": "Planteray Grande Réserve",
    "name_kz": "Planteray Grande Réserve",
    "name_en": "Planteray Grande Réserve",
    "price": 1990,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00439"
  },
  {
    "category_ru": "Ром",
    "category_kz": "Ром",
    "category_en": "Rum",
    "id": "b-00440-44",
    "type": "bar",
    "category_id": "rum",
    "name_ru": "Planteray Original Dark",
    "name_kz": "Planteray Original Dark",
    "name_en": "Planteray Original Dark",
    "price": 1690,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00440"
  },
  {
    "category_ru": "Ром",
    "category_kz": "Ром",
    "category_en": "Rum",
    "id": "b-00438-45",
    "type": "bar",
    "category_id": "rum",
    "name_ru": "Planteray 3 Stars White",
    "name_kz": "Planteray 3 Stars White",
    "name_en": "Planteray 3 Stars White",
    "price": 1490,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00438"
  },
  {
    "category_ru": "Текила",
    "category_kz": "Текила",
    "category_en": "Tequila",
    "id": "b-00437-46",
    "type": "bar",
    "category_id": "tequila",
    "name_ru": "Jose Cuervo Especial Reposado",
    "name_kz": "Jose Cuervo Especial Reposado",
    "name_en": "Jose Cuervo Especial Reposado",
    "price": 1790,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00437"
  },
  {
    "category_ru": "Текила",
    "category_kz": "Текила",
    "category_en": "Tequila",
    "id": "b-00436-47",
    "type": "bar",
    "category_id": "tequila",
    "name_ru": "Jose Cuervo Especial Silver",
    "name_kz": "Jose Cuervo Especial Silver",
    "name_en": "Jose Cuervo Especial Silver",
    "price": 1590,
    "weight": "50ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00436"
  },
  {
    "category_ru": "Лимонады",
    "category_kz": "Лимонадтар",
    "category_en": "Lemonades",
    "id": "b-00134-56",
    "type": "bar",
    "category_id": "lemonades",
    "name_ru": "Виноград - Вишня",
    "name_kz": "Жүзім - Шие",
    "name_en": "Grape - Cherry",
    "price": 2990,
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00134",
    "weight": "1L"
  },
  {
    "id": "b-lemonade-kiwi-basil",
    "type": "bar",
    "source_article": "lemonade-kiwi-basil",
    "category_id": "lemonades",
    "category_ru": "Лимонады",
    "category_kz": "Лимонадтар",
    "category_en": "Lemonades",
    "name_ru": "Киви - Базилик",
    "name_kz": "Киви - Базилик",
    "name_en": "Kiwi - Basil",
    "price": 2990,
    "weight": "1L",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": ""
  },
  {
    "category_ru": "Лимонады",
    "category_kz": "Лимонадтар",
    "category_en": "Lemonades",
    "id": "b-00136-59",
    "type": "bar",
    "category_id": "lemonades",
    "name_ru": "Маракуйя - Ананас",
    "name_kz": "Маракуйя - Ананас",
    "name_en": "Passion Fruit - Pineapple",
    "price": 2990,
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00136",
    "weight": "1L"
  },
  {
    "category_ru": "Лимонады",
    "category_kz": "Лимонадтар",
    "category_en": "Lemonades",
    "id": "b-00137-60",
    "type": "bar",
    "category_id": "lemonades",
    "name_ru": "Нектар",
    "name_kz": "Нектар",
    "name_en": "Nectar",
    "price": 2990,
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00137",
    "weight": "1L"
  },
  {
    "category_ru": "Вода и прохладительные напитки",
    "category_kz": "Су және салқын сусындар",
    "category_en": "Water & Soft Drinks",
    "id": "b-00109-64",
    "type": "bar",
    "category_id": "soft_drinks",
    "name_ru": "Вода Tassay",
    "name_kz": "Tassay суы",
    "name_en": "Tassay Water",
    "price": "990 / 2190",
    "weight": "250 / 750ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00109"
  },
  {
    "category_ru": "Вода и прохладительные напитки",
    "category_kz": "Су және салқын сусындар",
    "category_en": "Water & Soft Drinks",
    "id": "b-00110-62",
    "type": "bar",
    "category_id": "soft_drinks",
    "name_ru": "Pepsi / Mirinda / 7UP, стекло",
    "name_kz": "Pepsi / Mirinda / 7UP, шыны",
    "name_en": "Pepsi / Mirinda / 7UP, glass bottle",
    "price": 1290,
    "weight": "250ml",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00110"
  },
  {
    "category_ru": "Вода и прохладительные напитки",
    "category_kz": "Су және салқын сусындар",
    "category_en": "Water & Soft Drinks",
    "id": "b-00006-63",
    "type": "bar",
    "category_id": "soft_drinks",
    "name_ru": "Pepsi / Mirinda / 7UP",
    "name_kz": "Pepsi / Mirinda / 7UP",
    "name_en": "Pepsi / Mirinda / 7UP",
    "price": 1890,
    "weight": "1L",
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00006"
  },
  {
    "id": "b-soft-juice-assorted",
    "type": "bar",
    "source_article": "soft-juice-assorted",
    "category_id": "soft_drinks",
    "category_ru": "Вода и прохладительные напитки",
    "category_kz": "Су және салқын сусындар",
    "category_en": "Water & Soft Drinks",
    "name_ru": "Сок в ассортименте",
    "name_kz": "Шырын ассортименті",
    "name_en": "Assorted Juice",
    "price": 2090,
    "weight": "1L",
    "composition_ru": "Вишнёвый, яблочный, апельсиновый",
    "composition_kz": "Шие, алма, апельсин",
    "composition_en": "Cherry, apple, orange"
  },
  {
    "category_ru": "Авторский чай",
    "category_kz": "Авторлық шай",
    "category_en": "Signature Tea",
    "id": "b-00018-75",
    "type": "bar",
    "category_id": "signature_tea",
    "name_ru": "Ташкентский чай",
    "name_kz": "Ташкент шайы",
    "name_en": "Tashkent Tea",
    "price": 2590,
    "composition_ru": "Авторская чайная смесь",
    "composition_kz": "Авторлық шай қоспасы",
    "composition_en": "Signature tea blend",
    "source_article": "00018",
    "weight": "800ml"
  },
  {
    "id": "b-tea-ginger",
    "type": "bar",
    "source_article": "tea-ginger",
    "category_id": "signature_tea",
    "category_ru": "Авторский чай",
    "category_kz": "Авторлық шай",
    "category_en": "Signature Tea",
    "name_ru": "Имбирный",
    "name_kz": "Зімбір шайы",
    "name_en": "Ginger Tea",
    "price": 2590,
    "weight": "800ml",
    "composition_ru": "Чай с имбирём",
    "composition_kz": "Зімбір қосылған шай",
    "composition_en": "Tea with ginger"
  },
  {
    "id": "b-tea-raspberry-grapefruit",
    "type": "bar",
    "source_article": "tea-raspberry-grapefruit",
    "category_id": "signature_tea",
    "category_ru": "Авторский чай",
    "category_kz": "Авторлық шай",
    "category_en": "Signature Tea",
    "name_ru": "Малина - Грейпфрут",
    "name_kz": "Таңқурай - Грейпфрут",
    "name_en": "Raspberry - Grapefruit Tea",
    "price": 2590,
    "weight": "800ml",
    "composition_ru": "Чай с малиной и грейпфрутом",
    "composition_kz": "Таңқурай мен грейпфрут қосылған шай",
    "composition_en": "Tea with raspberry and grapefruit"
  },
  {
    "id": "b-tea-seabuckthorn-orange",
    "type": "bar",
    "source_article": "tea-seabuckthorn-orange",
    "category_id": "signature_tea",
    "category_ru": "Авторский чай",
    "category_kz": "Авторлық шай",
    "category_en": "Signature Tea",
    "name_ru": "Облепиха - Апельсин",
    "name_kz": "Шырғанақ - Апельсин",
    "name_en": "Sea Buckthorn - Orange Tea",
    "price": 2590,
    "weight": "800ml",
    "composition_ru": "Чай с облепихой и апельсином",
    "composition_kz": "Шырғанақ пен апельсин қосылған шай",
    "composition_en": "Tea with sea buckthorn and orange"
  },
  {
    "category_ru": "Авторский чай",
    "category_kz": "Авторлық шай",
    "category_en": "Signature Tea",
    "id": "b-00107-77",
    "type": "bar",
    "category_id": "signature_tea",
    "name_ru": "Чай с молоком",
    "name_kz": "Сүт қосылған шай",
    "name_en": "Tea with Milk",
    "price": 1790,
    "composition_ru": "Чай и молоко",
    "composition_kz": "Шай мен сүт",
    "composition_en": "Tea and milk",
    "source_article": "00107",
    "weight": "800ml"
  },
  {
    "category_ru": "Листовой чай",
    "category_kz": "Жапырақты шай",
    "category_en": "Loose-Leaf Tea",
    "id": "b-00012-68",
    "type": "bar",
    "category_id": "loose_leaf_tea",
    "name_ru": "Ассам",
    "name_kz": "Ассам",
    "name_en": "Ассам",
    "price": 1590,
    "composition_ru": "Чёрный листовой чай",
    "composition_kz": "Қара жапырақты шай",
    "composition_en": "Black loose-leaf tea",
    "source_article": "00012",
    "weight": "800ml"
  },
  {
    "category_ru": "Листовой чай",
    "category_kz": "Жапырақты шай",
    "category_en": "Loose-Leaf Tea",
    "id": "b-00013-73",
    "type": "bar",
    "category_id": "loose_leaf_tea",
    "name_ru": "Сенча",
    "name_kz": "Сенча",
    "name_en": "Сенча",
    "price": 1590,
    "composition_ru": "Японский зелёный листовой чай",
    "composition_kz": "Жапон көк жапырақты шайы",
    "composition_en": "Japanese green loose-leaf tea",
    "source_article": "00013",
    "weight": "800ml"
  },
  {
    "category_ru": "Листовой чай",
    "category_kz": "Жапырақты шай",
    "category_en": "Loose-Leaf Tea",
    "id": "b-00015-72",
    "type": "bar",
    "category_id": "loose_leaf_tea",
    "name_ru": "Ройбуш",
    "name_kz": "Ройбуш",
    "name_en": "Ройбуш",
    "price": 1590,
    "composition_ru": "Травяной листовой чай",
    "composition_kz": "Шөпті жапырақты шай",
    "composition_en": "Herbal loose-leaf tea",
    "source_article": "00015",
    "weight": "800ml"
  },
  {
    "category_ru": "Листовой чай",
    "category_kz": "Жапырақты шай",
    "category_en": "Loose-Leaf Tea",
    "id": "b-00014-76",
    "type": "bar",
    "category_id": "loose_leaf_tea",
    "name_ru": "Эрл Грей",
    "name_kz": "Эрл Грей",
    "name_en": "Эрл Грей",
    "price": 1590,
    "composition_ru": "Чёрный листовой чай с бергамотом",
    "composition_kz": "Бергамот қосылған қара жапырақты шай",
    "composition_en": "Black loose-leaf tea with bergamot",
    "source_article": "00014",
    "weight": "800ml"
  },
  {
    "category_ru": "Листовой чай",
    "category_kz": "Жапырақты шай",
    "category_en": "Loose-Leaf Tea",
    "id": "b-00011-69",
    "type": "bar",
    "category_id": "loose_leaf_tea",
    "name_ru": "Жасмин",
    "name_kz": "Жасмин",
    "name_en": "Jasmine",
    "price": 1590,
    "composition_ru": "Зелёный листовой чай с жасмином",
    "composition_kz": "Жасмин қосылған көк жапырақты шай",
    "composition_en": "Green loose-leaf tea with jasmine",
    "source_article": "00011",
    "weight": "800ml"
  },
  {
    "category_ru": "Листовой чай",
    "category_kz": "Жапырақты шай",
    "category_en": "Loose-Leaf Tea",
    "id": "b-00016-74",
    "type": "bar",
    "category_id": "loose_leaf_tea",
    "name_ru": "Султан",
    "name_kz": "Сұлтан",
    "name_en": "Sultan",
    "price": 1590,
    "composition_ru": "Листовой чай",
    "composition_kz": "Жапырақты шай",
    "composition_en": "Loose-leaf tea",
    "source_article": "00016",
    "weight": "800ml"
  },
  {
    "category_ru": "Добавки к чаю",
    "category_kz": "Шайға қосымшалар",
    "category_en": "Tea Add-ons",
    "id": "b-00140-51",
    "type": "bar",
    "category_id": "tea_addons",
    "name_ru": "Лимон",
    "name_kz": "Лимон",
    "name_en": "Лимон",
    "price": 590,
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00140",
    "weight": ""
  },
  {
    "category_ru": "Добавки к чаю",
    "category_kz": "Шайға қосымшалар",
    "category_en": "Tea Add-ons",
    "id": "b-00141-52",
    "type": "bar",
    "category_id": "tea_addons",
    "name_ru": "Мёд",
    "name_kz": "Мёд",
    "name_en": "Мёд",
    "price": 590,
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00141",
    "weight": ""
  },
  {
    "category_ru": "Добавки к чаю",
    "category_kz": "Шайға қосымшалар",
    "category_en": "Tea Add-ons",
    "id": "b-00142-53",
    "type": "bar",
    "category_id": "tea_addons",
    "name_ru": "Молоко",
    "name_kz": "Молоко",
    "name_en": "Молоко",
    "price": 590,
    "composition_ru": "",
    "composition_kz": "",
    "composition_en": "",
    "source_article": "00142",
    "weight": ""
  }
];

const TRANSLATIONS = {
  "RU": {
    "header_subtitle": "Lounge · Bar · Kitchen",
    "hero_title": "Меню",
    "hero_description": "Кухня, мангал и напитки",
    "search_placeholder": "Поиск блюд и напитков...",
    "search_label": "Поиск по меню",
    "clear_search": "Очистить поиск",
    "nav_kitchen": "КУХНЯ",
    "nav_bar": "БАР",
    "modal_ingredients": "Состав",
    "modal_close": "ЗАКРЫТЬ",
    "featured_title": "Выбор NECTAR",
    "featured_subtitle": "То, что мы рекомендуем попробовать",
    "card_hint": "Нажмите на блюдо, чтобы посмотреть полный состав",
    "tag_spicy": "Острое",
    "tag_vegetarian": "Вегетарианское",
    "unavailable": "Временно недоступно",
    "info_service": "Обслуживание",
    "info_service_value": "10%",
    "info_call": "Позвонить",
    "tab_menu": "Меню",
    "tab_info": "Инфо",
    "info_title": "Информация",
    "info_subtitle": "Контакты и важная информация",
    "info_address_label": "Адрес",
    "info_address": "Дулати даңғылы 1а, Архат шағынауданы, Алматы",
    "info_open_map": "Открыть в 2GIS",
    "info_phone_label": "Телефон",
    "info_hours": "Ежедневно · 14:00–01:00",
    "info_consumer": "Уголок потребителя",
    "info_license": "Лицензия и регистрация",
    "info_license_desc": "Информация о регистрации и разрешительных документах предоставляется гостям по запросу.",
    "info_rules": "Правила обслуживания",
    "info_rules_desc": "Мы заботимся о комфортной атмосфере и просим гостей соблюдать правила заведения.",
    "info_feedback": "Книга отзывов",
    "info_feedback_desc": "Книга отзывов и предложений предоставляется по запросу у менеджера.",
    "nothing_found": "Ничего не найдено",
    "try_another_search": "Попробуйте изменить запрос."
    ,"loading_menu": "Готовим меню"
    ,"offline_message": "Офлайн · сохранённое меню"
  },
  "KZ": {
    "header_subtitle": "Lounge · Bar · Kitchen",
    "hero_title": "Мәзір",
    "hero_description": "Асхана, мангал және сусындар",
    "search_placeholder": "Тағамдар мен сусындарды іздеу...",
    "search_label": "Мәзірден іздеу",
    "clear_search": "Іздеуді тазарту",
    "nav_kitchen": "АСХАНА",
    "nav_bar": "БАР",
    "modal_ingredients": "Құрамы",
    "modal_close": "ЖАБУ",
    "featured_title": "NECTAR таңдауы",
    "featured_subtitle": "Біз ұсынатын таңдаулы тағамдар",
    "card_hint": "Толық құрамын көру үшін тағамды басыңыз",
    "tag_spicy": "Ащы",
    "tag_vegetarian": "Вегетариандық",
    "unavailable": "Уақытша қолжетімсіз",
    "info_service": "Қызмет көрсету",
    "info_service_value": "10%",
    "info_call": "Қоңырау шалу",
    "tab_menu": "Мәзір",
    "tab_info": "Ақпарат",
    "info_title": "Ақпарат",
    "info_subtitle": "Байланыс деректері және маңызды ақпарат",
    "info_address_label": "Мекенжай",
    "info_address": "Алматы",
    "info_open_map": "2GIS картасынан ашу",
    "info_phone_label": "Телефон",
    "info_hours": "Күн сайын · 14:00–01:00",
    "info_consumer": "Тұтынушы бұрышы",
    "info_license": "Лицензия және тіркеу",
    "info_license_desc": "Тіркеу және рұқсат құжаттары туралы ақпарат қонақтарға сұраныс бойынша беріледі.",
    "info_rules": "Қызмет көрсету ережелері",
    "info_rules_desc": "Біз жайлы атмосфераға мән береміз және қонақтардан мекеме ережелерін сақтауды сұраймыз.",
    "info_feedback": "Пікірлер кітабы",
    "info_feedback_desc": "Пікірлер мен ұсыныстар кітабы менеджерден сұраныс бойынша беріледі.",
    "nothing_found": "Ештеңе табылмады",
    "try_another_search": "Іздеу сұрауын өзгертіп көріңіз."
    ,"loading_menu": "Мәзір дайындалуда"
    ,"offline_message": "Офлайн · сақталған мәзір"
  },
  "EN": {
    "header_subtitle": "Lounge · Bar · Kitchen",
    "hero_title": "Menu",
    "hero_description": "Kitchen, charcoal grill and drinks",
    "search_placeholder": "Search dishes and drinks...",
    "search_label": "Search the menu",
    "clear_search": "Clear search",
    "nav_kitchen": "KITCHEN",
    "nav_bar": "BAR",
    "modal_ingredients": "Ingredients",
    "modal_close": "CLOSE",
    "featured_title": "NECTAR Selection",
    "featured_subtitle": "A selection we recommend trying",
    "card_hint": "Tap a dish to view full details",
    "tag_spicy": "Spicy",
    "tag_vegetarian": "Vegetarian",
    "unavailable": "Temporarily unavailable",
    "info_service": "Service charge",
    "info_service_value": "10%",
    "info_call": "Call",
    "tab_menu": "Menu",
    "tab_info": "Info",
    "info_title": "Information",
    "info_subtitle": "Contact details and useful information",
    "info_address_label": "Address",
    "info_address": "1A Dulati Avenue, Arkhat Microdistrict, Almaty",
    "info_open_map": "Open in 2GIS",
    "info_phone_label": "Phone",
    "info_hours": "Daily · 14:00–01:00",
    "info_consumer": "Consumer Information",
    "info_license": "License & Registration",
    "info_license_desc": "Registration and permit information is available to guests upon request.",
    "info_rules": "Service Rules",
    "info_rules_desc": "We care about a comfortable atmosphere and ask guests to follow the venue rules.",
    "info_feedback": "Guest Feedback",
    "info_feedback_desc": "The guest comments and suggestions book is available from a manager upon request.",
    "nothing_found": "Nothing found",
    "try_another_search": "Try a different search."
    ,"loading_menu": "Preparing the menu"
    ,"offline_message": "Offline · saved menu"
  }
};
