const MENU = [

  {
    "id": "1-1",
    "category_ru": "Холодные закуски",
    "category_kz": "Суық тағамдар",
    "category_en": "Cold Appetizers",
    "name_ru": "Мясное плато",
    "name_kz": "Ет табағы",
    "name_en": "Meat Platter",
    "price": 4990,
    "weight": "350г",
    "composition_ru": "Казы, жая, жал, отварной язык, подается с хреном и горчицей.",
    "composition_kz": "Қазы, жая, жал, пісірілген тіл, желкек және қышамен бірге ұсынылады.",
    "composition_en": "Kazy, zhaya, zhal, boiled tongue, served with horseradish and mustard.",
    "note": ""
  },
  {
    "id": "1-2",
    "category_ru": "Холодные закуски",
    "category_kz": "Суық тағамдар",
    "category_en": "Cold Appetizers",
    "name_ru": "Домашние соленья",
    "name_kz": "Үйде тұздалған көкөністер",
    "name_en": "Homemade Pickles",
    "price": 2890,
    "weight": "400г",
    "composition_ru": "Огурцы соленые, помидоры черри, капуста квашеная, чеснок маринованный, перец острый.",
    "composition_kz": "Тұздалған қияр, шие қызанақтары, ашытылған қырыққабат, маринадталған сарымсақ, ащы бұрыш.",
    "composition_en": "Pickled cucumbers, cherry tomatoes, sauerkraut, marinated garlic, and hot pepper.",
    "note": ""
  },
  {
    "id": "1-3",
    "category_ru": "Холодные закуски",
    "category_kz": "Суық тағамдар",
    "category_en": "Cold Appetizers",
    "name_ru": "Овощная нарезка",
    "name_kz": "Көкөніс табағы",
    "name_en": "Fresh Vegetable Platter",
    "price": 2890,
    "weight": "400г",
    "composition_ru": "Томаты свежие, огурцы, болгарский перец, редис, зелень, микс салата.",
    "composition_kz": "Жаңа піскен қызанақ, қияр, болгар бұрышы, шалғам, көк шөптер және салат миксі.",
    "composition_en": "Fresh tomatoes, cucumbers, bell pepper, radish, fresh herbs, and mixed salad leaves.",
    "note": ""
  },
  {
    "id": "1-4",
    "category_ru": "Холодные закуски",
    "category_kz": "Суық тағамдар",
    "category_en": "Cold Appetizers",
    "name_ru": "Рыбное ассорти",
    "name_kz": "Балық ассортиі",
    "name_en": "Fish Assortment",
    "price": 5590,
    "weight": "300г",
    "composition_ru": "Семга слабосоленая, масляная рыба, балык из судака, лимон, маслины.",
    "composition_kz": "Аздап тұздалған албырт, майлы балық, көксеркеден жасалған балық балығы, лимон, зәйтүн.",
    "composition_en": "Lightly salted salmon, escolar, pike-perch balyk, lemon, and olives.",
    "note": ""
  },
  {
    "id": "1-5",
    "category_ru": "Холодные закуски",
    "category_kz": "Суық тағамдар",
    "category_en": "Cold Appetizers",
    "name_ru": "Капрезе",
    "name_kz": "Капрезе",
    "name_en": "Caprese",
    "price": 2790,
    "weight": "250г",
    "composition_ru": "Свежие томаты, сыр моцарелла, соус песто, бальзамический крем, базилик.",
    "composition_kz": "Жаңа піскен қызанақ, моцарелла ірімшігі, песто соусы, бальзамикалық крем, базилик.",
    "composition_en": "Fresh tomatoes, mozzarella, pesto sauce, balsamic cream, and basil.",
    "note": ""
  },
  {
    "id": "1-6",
    "category_ru": "Холодные закуски",
    "category_kz": "Суық тағамдар",
    "category_en": "Cold Appetizers",
    "name_ru": "Сырное плато",
    "name_kz": "Ірімшік табағы",
    "name_en": "Cheese Platter",
    "price": 4990,
    "weight": "320г",
    "composition_ru": "Пармезан, дор блю, камамбер, маасдам, мед, грецкие орехи, виноград.",
    "composition_kz": "Пармезан, дорблю, камамбер, маасдам ірімшіктері, бал, грек жаңғағы, жүзім.",
    "composition_en": "Parmesan, Roquefort-style blue cheese, Camembert, Maasdam, honey, walnuts, and grapes.",
    "note": ""
  },

  {
    "id": "2-1",
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "name_ru": "Свежий овощной салат",
    "name_kz": "Жаңа піскен көкөніс салаты",
    "name_en": "Fresh Vegetable Salad",
    "price": 1990,
    "weight": "250г",
    "composition_ru": "Огурцы, помидоры, болгарский перец, красный лук, заправка на выбор (масло / сметана).",
    "composition_kz": "Қияр, қызанақ, болгар бұрышы, қызыл пияз, таңдауыңыз бойынша тұздық (май / қаймақ).",
    "composition_en": "Cucumbers, tomatoes, bell pepper, red onion, with a choice of dressing (oil / sour cream).",
    "note": ""
  },
  {
    "id": "2-2",
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "name_ru": "Аччик-чучук",
    "name_kz": "Аччик-чучук",
    "name_en": "Achchik-Chuchuk (Spicy Tomato Salad)",
    "price": 1790,
    "weight": "200г",
    "composition_ru": "Спелые томаты, тонко нарезанный репчатый лук, острый перец.",
    "composition_kz": "Піскен қызанақ, жұқа туралған пияз, ащы бұрыш.",
    "composition_en": "Ripe tomatoes, thinly sliced onion, and hot pepper.",
    "note": ""
  },
  {
    "id": "2-3",
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "name_ru": "Цезарь с курицей",
    "name_kz": "Тауық етімен Цезарь",
    "name_en": "Caesar with Chicken",
    "price": 2590,
    "weight": "280г",
    "composition_ru": "Куриное филе гриль, листья салата романо, томаты черри, сыр пармезан, гренки, соус цезарь.",
    "composition_kz": "Грильде дайындалған тауық филесі, романо салатының жапырақтары, шие қызанақтары, пармезан ірімшігі, кептірілген нан тілімдері, Цезарь соусы.",
    "composition_en": "Grilled chicken fillet, romaine lettuce, cherry tomatoes, Parmesan, croutons, and Caesar dressing.",
    "note": ""
  },
  {
    "id": "2-4",
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "name_ru": "Хрустящие баклажаны",
    "name_kz": "Қытырлақ баклажан",
    "name_en": "Crispy Eggplant Salad",
    "price": 2790,
    "weight": "260г",
    "composition_ru": "Баклажаны в крахмале во фритюре, томаты свежие, кинза, кунжут, кисло-сладкий соус.",
    "composition_kz": "Крахмалға аунатылып, фритюрде қуырылған баклажан, жаңа піскен қызанақ, кинза, күнжіт, тәтті-қышқыл соус.",
    "composition_en": "Starch-coated deep-fried eggplant, fresh tomatoes, cilantro, sesame, and sweet-and-sour sauce.",
    "note": ""
  },
  {
    "id": "2-5",
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "name_ru": "Греческий салат",
    "name_kz": "Грек салаты",
    "name_en": "Greek Salad",
    "price": 2490,
    "weight": "300г",
    "composition_ru": "Томаты, огурцы, перец болгарский, маслины каламата, сыр фета, оливковое масло, орегано.",
    "composition_kz": "Қызанақ, қияр, болгар бұрышы, Каламата зәйтүні, фета ірімшігі, зәйтүн майы, орегано.",
    "composition_en": "Tomatoes, cucumbers, bell pepper, Kalamata olives, feta cheese, olive oil, and oregano.",
    "note": ""
  },
  {
    "id": "2-6",
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "name_ru": "Теплый салат с кониной",
    "name_kz": "Жылы жылқы еті салаты",
    "name_en": "Warm Horse Meat Salad",
    "price": 2990,
    "weight": "270г",
    "composition_ru": "Отварная конина, микс салатов, вяленые томаты, кедровые орехи, фирменная заправка.",
    "composition_kz": "Пісірілген жылқы еті, салат миксі, кептірілген қызанақ, қарағай жаңғағы, фирмалық тұздық.",
    "composition_en": "Boiled horse meat, mixed salad leaves, sun-dried tomatoes, pine nuts, and signature dressing.",
    "note": ""
  },
  {
    "id": "2-7",
    "category_ru": "Салаты",
    "category_kz": "Салаттар",
    "category_en": "Salads",
    "name_ru": "Салат с креветками и рукколой",
    "name_kz": "Асшаян және руккола салаты",
    "name_en": "Shrimp & Rocket Salad",
    "price": 3990,
    "weight": "240г",
    "composition_ru": "Тигровые креветки, руккола, томаты черри, сыр пармезан, бальзамик.",
    "composition_kz": "Жолбарыс асшаяндары, руккола, шие қызанақтары, пармезан ірімшігі, бальзамик.",
    "composition_en": "Tiger prawns, arugula, cherry tomatoes, Parmesan, and balsamic glaze.",
    "note": ""
  },

  {
    "id": "3-1",
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Hot Appetizers",
    "name_ru": "Креветки темпура",
    "name_kz": "Темпура асшаяндары",
    "name_en": "Tempura Shrimp",
    "price": 3290,
    "weight": "220г",
    "composition_ru": "Тигровые креветки в хрустящем кляре темпура, кисло-сладкий соус.",
    "composition_kz": "Тигр асшаяндары қытырлақ темпура қамырына оралып, тәтті-қышқыл соуспен бірге ұсынылады.",
    "composition_en": "Tiger prawns in a crispy tempura batter, served with sweet-and-sour sauce.",
    "note": ""
  },
  {
    "id": "3-2",
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Hot Appetizers",
    "name_ru": "Клаб-сэндвич с курицей",
    "name_kz": "Тауық етімен клаб-сэндвич",
    "name_en": "Chicken Club Sandwich",
    "price": 3190,
    "weight": "350г",
    "composition_ru": "Тостовый хлеб, куриное филе, бекон, сыр чеддер, томаты, айсберг, картофель фри.",
    "composition_kz": "Тост наны, тауық филесі, бекон, чеддер ірімшігі, қызанақ, айсберг салаты, картоп фри.",
    "composition_en": "Toast bread, chicken fillet, bacon, Cheddar cheese, tomatoes, iceberg lettuce, and French fries.",
    "note": ""
  },
  {
    "id": "3-3",
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Hot Appetizers",
    "name_ru": "Кесадилья с курицей",
    "name_kz": "Тауық етімен кесадилья",
    "name_en": "Chicken Quesadilla",
    "price": 2990,
    "weight": "300г",
    "composition_ru": "Пшеничная тортилья, куриное филе, болгарский перец, сыр моцарелла, халапеньо, соус сальса.",
    "composition_kz": "Бидай тортильясы, тауық филесі, болгар бұрышы, моцарелла ірімшігі, халапеньо, сальса соусы.",
    "composition_en": "Wheat tortilla, chicken fillet, bell pepper, mozzarella cheese, jalapeño, and salsa.",
    "note": ""
  },
  {
    "id": "3-4",
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Hot Appetizers",
    "name_ru": "Чебуреки",
    "name_kz": "Шебуректер",
    "name_en": "Chebureki",
    "price": 2490,
    "weight": "300г",
    "composition_ru": "Тонкое хрустящее тесто, сочный фарш из говядины и лука, специи.",
    "composition_kz": "Жұқа қытырлақ қамыр, шырынды сиыр еті мен пияздан жасалған фарш, дәмдеуіштер.",
    "composition_en": "Thin crispy dough filled with juicy minced beef, onion, and spices.",
    "note": ""
  },
  {
    "id": "3-5",
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Hot Appetizers",
    "name_ru": "Куриные наггетсы",
    "name_kz": "Тауық наггетстері",
    "name_en": "Chicken Nuggets",
    "price": 2490,
    "weight": "250г",
    "composition_ru": "Куриное филе в панировочных сухарях, подается с соусом.",
    "composition_kz": "Нан үгіндісіне аунатылған тауық филесі, соуспен бірге ұсынылады.",
    "composition_en": "Chicken fillet in breadcrumbs, served with sauce.",
    "note": ""
  },
  {
    "id": "3-6",
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Hot Appetizers",
    "name_ru": "Пивной сет",
    "name_kz": "Сыраға арналған сет",
    "name_en": "Beer Snack Set",
    "price": 6990,
    "weight": "650г",
    "composition_ru": "Ассорти популярных пивных закусок с соусами тартар и кетчуп.",
    "composition_kz": "Тартар және кетчуп соустарымен ұсынылатын танымал сыраға арналған тіскебасарлар ассортиі.",
    "composition_en": "An assortment of popular beer snacks served with tartar sauce and ketchup.",
    "note": ""
  },
  {
    "id": "3-7",
    "category_ru": "Горячие закуски",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Hot Appetizers",
    "name_ru": "Креветки с чесноком",
    "name_kz": "Сарымсақ қосылған асшаяндар",
    "name_en": "Garlic Shrimp",
    "price": 3990,
    "weight": "250г",
    "composition_ru": "Креветки в панцире, обжаренные с чесноком, соевым соусом и перцем чили.",
    "composition_kz": "Қабығымен бірге сарымсақ, соя соусы және чили бұрышымен қуырылған асшаяндар.",
    "composition_en": "Shell-on shrimp sautéed with garlic, soy sauce, and chili pepper.",
    "note": ""
  },

  {
    "id": "4-1",
    "category_ru": "Снэки",
    "category_kz": "Снэктер",
    "category_en": "Snacks",
    "name_ru": "Фисташки",
    "name_kz": "Пісте",
    "name_en": "Pistachios",
    "price": 1890,
    "weight": "100г",
    "composition_ru": "Жареные соленые фисташки.",
    "composition_kz": "Қуырылған тұзды пісте.",
    "composition_en": "Roasted salted pistachios.",
    "note": ""
  },
  {
    "id": "4-2",
    "category_ru": "Снэки",
    "category_kz": "Снэктер",
    "category_en": "Snacks",
    "name_ru": "Чесночные гренки",
    "name_kz": "Сарымсақты гренкалар",
    "name_en": "Garlic Croutons",
    "price": 1290,
    "weight": "150г",
    "composition_ru": "Ржаной хлеб, обжаренный в масле с чесночным соусом и зеленью.",
    "composition_kz": "Майда сарымсақ соусы және көк шөптермен қуырылған қара бидай наны.",
    "composition_en": "Rye bread fried in oil with garlic sauce and fresh herbs.",
    "note": ""
  },
  {
    "id": "4-3",
    "category_ru": "Снэки",
    "category_kz": "Снэктер",
    "category_en": "Snacks",
    "name_ru": "Сыр косичка",
    "name_kz": "Шашылған ірімшік",
    "name_en": "Smoked String Cheese",
    "price": 1490,
    "weight": "100г",
    "composition_ru": "Традиционный копченый сыр-соломка.",
    "composition_kz": "Дәстүрлі ысталған талшықты ірімшік.",
    "composition_en": "Traditional smoked string cheese.",
    "note": ""
  },
  {
    "id": "4-4",
    "category_ru": "Снэки",
    "category_kz": "Снэктер",
    "category_en": "Snacks",
    "name_ru": "Арахис",
    "name_kz": "Жержаңғақ",
    "name_en": "Peanuts",
    "price": 990,
    "weight": "100г",
    "composition_ru": "Арахис соленый жареный.",
    "composition_kz": "Қуырылған тұзды жержаңғақ.",
    "composition_en": "Roasted salted peanuts.",
    "note": ""
  },

  {
    "id": "5-1",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Окрошка",
    "name_kz": "Окрошка",
    "name_en": "Okroshka",
    "price": 1990,
    "weight": "350г",
    "composition_ru": "Говядина отварная, огурцы, редис, яйцо, зелень, квас / кефир.",
    "composition_kz": "Пісірілген сиыр еті, қияр, шалғам, жұмыртқа, көк шөптер, квас / айран.",
    "composition_en": "Boiled beef, cucumbers, radish, egg, fresh herbs, kvass / kefir.",
    "note": ""
  },
  {
    "id": "5-2",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Куриный суп с лапшой",
    "name_kz": "Кеспе қосылған тауық сорпасы",
    "name_en": "Chicken Noodle Soup",
    "price": 1990,
    "weight": "350г",
    "composition_ru": "Ароматный куриный бульон, домашняя лапша, куриное филе, морковь, зелень.",
    "composition_kz": "Хош иісті тауық сорпасы, үй кеспесі, тауық филесі, сәбіз, көк шөптер.",
    "composition_en": "Aromatic chicken broth, homemade noodles, chicken fillet, carrots, and fresh herbs.",
    "note": ""
  },
  {
    "id": "5-3",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Солянка",
    "name_kz": "Солянка",
    "name_en": "Solyanka",
    "price": 2290,
    "weight": "350г",
    "composition_ru": "Ассорти мясных деликатесов, соленые огурцы, маслины, лимон, сметана.",
    "composition_kz": "Ет деликатестерінің ассортиі, тұздалған қияр, зәйтүн, лимон, қаймақ.",
    "composition_en": "Assorted meat delicacies, pickles, olives, lemon, and sour cream.",
    "note": ""
  },
  {
    "id": "5-4",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Том Ям",
    "name_kz": "Том Ям",
    "name_en": "Tom Yum",
    "price": 3290,
    "weight": "400г",
    "composition_ru": "Пряный тайский суп, креветки, кальмары, шампиньоны, кокосовое молоко, рис.",
    "composition_kz": "Ащылау тай сорпасы, асшаяндар, кальмар, шампиньондар, кокос сүті, күріш.",
    "composition_en": "Spicy Thai soup with shrimp, squid, mushrooms, coconut milk, and rice.",
    "note": ""
  },
  {
    "id": "5-5",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Рамен с говядиной",
    "name_kz": "Сиыр етімен рамен",
    "name_en": "Beef Ramen",
    "price": 2990,
    "weight": "450г",
    "composition_ru": "Наваристый бульон, лапша рамен, говядина слайсы, яйцо маринованное, нори, лук-порей.",
    "composition_kz": "Қою сорпа, рамен кеспесі, сиыр етінің тілімдері, маринадталған жұмыртқа, нори, порей пиязы.",
    "composition_en": "Rich broth, ramen noodles, sliced beef, marinated egg, nori, and leek.",
    "note": ""
  },
  {
    "id": "5-6",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Рамен с курицей",
    "name_kz": "Тауық етімен рамен",
    "name_en": "Chicken Ramen",
    "price": 2790,
    "weight": "450г",
    "composition_ru": "Бульон, лапша рамен, куриное филе су-вид, яйцо, нори, зелень.",
    "composition_kz": "Сорпа, рамен кеспесі, су-вид әдісімен дайындалған тауық филесі, жұмыртқа, нори, көк шөптер.",
    "composition_en": "Broth, ramen noodles, sous-vide chicken fillet, egg, nori, and fresh herbs.",
    "note": ""
  },
  {
    "id": "5-7",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Чечевичный суп",
    "name_kz": "Жасымық сорпасы",
    "name_en": "Lentil Soup",
    "price": 1890,
    "weight": "350г",
    "composition_ru": "Красная чечевица, лук, морковь, подается с сухариками и лимоном.",
    "composition_kz": "Қызыл жасымық, пияз, сәбіз, кептірілген нан тілімдері және лимонмен бірге ұсынылады.",
    "composition_en": "Red lentils, onion, and carrots, served with croutons and lemon.",
    "note": ""
  },
  {
    "id": "5-8",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Шурпа",
    "name_kz": "Шорпа",
    "name_en": "Shurpa",
    "price": 2290,
    "weight": "400г",
    "composition_ru": "Традиционный мясной бульон из баранины, крупный картофель, морковь, лук.",
    "composition_kz": "Қой етінен дайындалған дәстүрлі ет сорпасы, ірі картоп, сәбіз, пияз.",
    "composition_en": "Traditional lamb broth with chunky potatoes, carrots, and onion.",
    "note": ""
  },
  {
    "id": "5-9",
    "category_ru": "Супы",
    "category_kz": "Сорпалар",
    "category_en": "Soups",
    "name_ru": "Пельмени",
    "name_kz": "Пельмендер",
    "name_en": "Pelmeni",
    "price": 2290,
    "weight": "300г",
    "composition_ru": "Домашние пельмени из говядины, подаются со сметаной или в бульоне.",
    "composition_kz": "Сиыр етінен жасалған үй пельмендері, қаймақпен немесе сорпамен бірге ұсынылады.",
    "composition_en": "Homemade beef dumplings, served with sour cream or in broth.",
    "note": ""
  },

  {
    "id": "6-1",
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және нан өнімдері",
    "category_en": "Pizza & Bakery",
    "name_ru": "Пепперони",
    "name_kz": "Пепперони",
    "name_en": "Pepperoni Pizza",
    "price": 3290,
    "weight": "500г",
    "composition_ru": "Томатный соус, моцарелла, колбаски пепперони, орегано.",
    "composition_kz": "Томат соусы, моцарелла, пепперони шұжықтары, орегано.",
    "composition_en": "Tomato sauce, mozzarella, pepperoni, and oregano.",
    "note": ""
  },
  {
    "id": "6-2",
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және нан өнімдері",
    "category_en": "Pizza & Bakery",
    "name_ru": "Маргарита",
    "name_kz": "Маргарита",
    "name_en": "Margherita Pizza",
    "price": 2990,
    "weight": "450г",
    "composition_ru": "Томатный соус, сыр моцарелла, свежие томаты, базилик.",
    "composition_kz": "Томат соусы, моцарелла ірімшігі, жаңа піскен қызанақ, базилик.",
    "composition_en": "Tomato sauce, mozzarella, fresh tomatoes, and basil.",
    "note": ""
  },
  {
    "id": "6-3",
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және нан өнімдері",
    "category_en": "Pizza & Bakery",
    "name_ru": "Курица и грибы",
    "name_kz": "Тауық еті және саңырауқұлақ қосылған",
    "name_en": "Chicken & Mushroom Pizza",
    "price": 3090,
    "weight": "520г",
    "composition_ru": "Сливочный соус, моцарелла, куриное филе, шампиньоны.",
    "composition_kz": "Кілегейлі соус, моцарелла, тауық филесі, шампиньондар.",
    "composition_en": "Cream sauce, mozzarella, chicken fillet, and mushrooms.",
    "note": ""
  },
  {
    "id": "6-4",
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және нан өнімдері",
    "category_en": "Pizza & Bakery",
    "name_ru": "Болоньезе",
    "name_kz": "Болоньезе",
    "name_en": "Bolognese Pizza",
    "price": 3190,
    "weight": "520г",
    "composition_ru": "Соус болоньезе (фарш из говядины), томатный соус, моцарелла, лук.",
    "composition_kz": "Болоньезе соусы (сиыр етінің фаршы), томат соусы, моцарелла, пияз.",
    "composition_en": "Bolognese sauce (minced beef), tomato sauce, mozzarella, and onion.",
    "note": ""
  },
  {
    "id": "6-5",
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және нан өнімдері",
    "category_en": "Pizza & Bakery",
    "name_ru": "Мексиканская",
    "name_kz": "Мексикалық пицца",
    "name_en": "Mexican Pizza",
    "price": 3390,
    "weight": "530г",
    "composition_ru": "Острый соус, моцарелла, говядина, болгарский перец, перец халапеньо, кукуруза.",
    "composition_kz": "Ащы соус, моцарелла, сиыр еті, болгар бұрышы, халапеньо, жүгері.",
    "composition_en": "Spicy sauce, mozzarella, beef, bell pepper, jalapeño, and corn.",
    "note": ""
  },
  {
    "id": "6-6",
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және нан өнімдері",
    "category_en": "Pizza & Bakery",
    "name_ru": "Хачапури по-аджарски",
    "name_kz": "Аджарша хачапури",
    "name_en": "Adjarian Khachapuri",
    "price": 2990,
    "weight": "400г",
    "composition_ru": "Дрожжевое тесто, обильная начинка из сыра сулугуни внутри и сверху.",
    "composition_kz": "Ашытқылы қамыр, іші мен үстіне молынан салынған сулугуни ірімшігі.",
    "composition_en": "Yeast dough generously filled and topped with Sulguni cheese.",
    "note": ""
  },
  {
    "id": "6-7",
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және нан өнімдері",
    "category_en": "Pizza & Bakery",
    "name_ru": "Хлебная корзина",
    "name_kz": "Нан себеті",
    "name_en": "Bread Basket",
    "price": 990,
    "weight": "250г",
    "composition_ru": "Ассорти фирменного хлеба собственного приготовления.",
    "composition_kz": "Өзіміз дайындайтын фирмалық нан түрлерінің ассортиі.",
    "composition_en": "Assortment of house-made signature breads.",
    "note": ""
  },
  {
    "id": "6-8",
    "category_ru": "Пицца и выпечка",
    "category_kz": "Пицца және нан өнімдері",
    "category_en": "Pizza & Bakery",
    "name_ru": "Лепешка из тандыра",
    "name_kz": "Тандыр наны",
    "name_en": "Tandoor Flatbread",
    "price": 790,
    "weight": "180г",
    "composition_ru": "Традиционная узбекская лепешка из тандыра.",
    "composition_kz": "Тандырда пісірілген дәстүрлі өзбек лепешкасы.",
    "composition_en": "Traditional Uzbek flatbread baked in a tandoor.",
    "note": ""
  },

  {
    "id": "7-1",
    "category_ru": "Паста",
    "category_kz": "Паста",
    "category_en": "Pasta",
    "name_ru": "Паста с морепродуктами",
    "name_kz": "Теңіз өнімдері қосылған паста",
    "name_en": "Seafood Pasta",
    "price": 3790,
    "weight": "350г",
    "composition_ru": "Паста фарфалле, морепродукты, сливки, чеснок, сыр пармезан.",
    "composition_kz": "Фарфалле пастасы, теңіз өнімдері, кілегей, сарымсақ, пармезан ірімшігі.",
    "composition_en": "Farfalle pasta, seafood, cream, garlic, and Parmesan cheese.",
    "note": ""
  },
  {
    "id": "7-2",
    "category_ru": "Паста",
    "category_kz": "Паста",
    "category_en": "Pasta",
    "name_ru": "Карбонара",
    "name_kz": "Карбонара",
    "name_en": "Carbonara",
    "price": 2990,
    "weight": "330г",
    "composition_ru": "Спагетти, бекон, яичный желток, сыр пармезан, черный перец, сливки.",
    "composition_kz": "Спагетти, бекон, жұмыртқаның сарыуызы, пармезан ірімшігі, қара бұрыш, кілегей.",
    "composition_en": "Spaghetti, bacon, egg yolk, Parmesan cheese, black pepper, and cream.",
    "note": ""
  },
  {
    "id": "7-3",
    "category_ru": "Паста",
    "category_kz": "Паста",
    "category_en": "Pasta",
    "name_ru": "Болоньезе",
    "name_kz": "Болоньезе",
    "name_en": "Bolognese",
    "price": 2990,
    "weight": "330г",
    "composition_ru": "Спагетти, классический мясной соус из говядины с томатами и зеленью.",
    "composition_kz": "Спагетти, қызанақ пен көк шөптер қосылған сиыр етінен дайындалған классикалық ет соусы.",
    "composition_en": "Spaghetti with classic beef meat sauce, tomatoes, and fresh herbs.",
    "note": ""
  },
  {
    "id": "7-4",
    "category_ru": "Паста",
    "category_kz": "Паста",
    "category_en": "Pasta",
    "name_ru": "Фетучини с курицей и грибами",
    "name_kz": "Тауық еті және саңырауқұлақ қосылған фетучини",
    "name_en": "Chicken & Mushroom Fettuccine",
    "price": 3190,
    "weight": "350г",
    "composition_ru": "Паста фетучини, куриное филе, шампиньоны, сливочный соус, пармезан.",
    "composition_kz": "Фетучини пастасы, тауық филесі, шампиньондар, кілегейлі соус, пармезан.",
    "composition_en": "Fettuccine pasta, chicken fillet, mushrooms, cream sauce, and Parmesan.",
    "note": ""
  },

  {
    "id": "8-1",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Куырдак",
    "name_kz": "Қуырдақ",
    "name_en": "Kuyrdak",
    "price": 3990,
    "weight": "350г",
    "composition_ru": "Традиционное жаркое из мяса и субпродуктов (печень, почки) с луком и картофелем.",
    "composition_kz": "Ет пен субөнімдерден (бауыр, бүйрек) пияз және картоп қосып дайындалған дәстүрлі қуырдақ.",
    "composition_en": "Traditional roast made with meat and offal (liver and kidneys), onion, and potatoes.",
    "note": ""
  },
  {
    "id": "8-2",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Плов",
    "name_kz": "Палау",
    "name_en": "Plov",
    "price": 2990,
    "weight": "350г",
    "composition_ru": "Рис лазер, баранина / говядина, желтая морковь, нут, специи, зира.",
    "composition_kz": "Лазер күріші, қой еті / сиыр еті, сары сәбіз, ноқат, дәмдеуіштер, зире.",
    "composition_en": "Lazer rice, lamb / beef, yellow carrots, chickpeas, spices, and cumin.",
    "note": ""
  },
  {
    "id": "8-3",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Чикенбургер",
    "name_kz": "Тауық бургері",
    "name_en": "Chicken Burger",
    "price": 2990,
    "weight": "350г",
    "composition_ru": "Булочка бриошь, куриная котлета в панировке, салат айсберг, томаты, соус.",
    "composition_kz": "Бриошь тоқашы, нан үгіндісіне аунатылған тауық котлеті, айсберг салаты, қызанақ, соус.",
    "composition_en": "Brioche bun, breaded chicken patty, iceberg lettuce, tomatoes, and sauce.",
    "note": ""
  },
  {
    "id": "8-4",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Бургер классический",
    "name_kz": "Классикалық бургер",
    "name_en": "Classic Burger",
    "price": 3290,
    "weight": "350г",
    "composition_ru": "Булочка бриошь, мраморная говяжья котлета, сыр чеддер, соленый огурец, соус.",
    "composition_kz": "Бриошь тоқашы, мәрмәр сиыр етінен жасалған котлет, чеддер ірімшігі, тұздалған қияр, соус.",
    "composition_en": "Brioche bun, marbled beef patty, Cheddar cheese, pickle, and sauce.",
    "note": ""
  },
  {
    "id": "8-5",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Бургер с грибами",
    "name_kz": "Саңырауқұлақ қосылған бургер",
    "name_en": "Mushroom Burger",
    "price": 3490,
    "weight": "370г",
    "composition_ru": "Говяжья котлета, карамелизированные грибы в соусе стаут, сыр, трюфельный соус.",
    "composition_kz": "Сиыр етінің котлеті, стаут соусындағы карамельденген саңырауқұлақтар, ірімшік, трюфель соусы.",
    "composition_en": "Beef patty, caramelized mushrooms in stout sauce, cheese, and truffle sauce.",
    "note": ""
  },
  {
    "id": "8-6",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Колбаски домашние",
    "name_kz": "Үй шұжықтары",
    "name_en": "Homemade Sausages",
    "price": 3290,
    "weight": "300г",
    "composition_ru": "Домашние колбаски на гриле, подаются с тушеной капустой и горчицей.",
    "composition_kz": "Үй шұжықтары грильде дайындалып, бұқтырылған қырыққабат және қышамен бірге ұсынылады.",
    "composition_en": "House-made sausages grilled and served with braised cabbage and mustard.",
    "note": ""
  },
  {
    "id": "8-7",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Колбаски куриные",
    "name_kz": "Тауық шұжықтары",
    "name_en": "Chicken Sausages",
    "price": 2990,
    "weight": "300г",
    "composition_ru": "Нежные куриные колбаски с зеленью и специями.",
    "composition_kz": "Жұмсақ тауық шұжықтары, көк шөптер мен дәмдеуіштер қосылған.",
    "composition_en": "Tender chicken sausages with fresh herbs and spices.",
    "note": ""
  },
  {
    "id": "8-8",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Говядина вок",
    "name_kz": "Воктағы сиыр еті",
    "name_en": "Wok Beef",
    "price": 3690,
    "weight": "350г",
    "composition_ru": "Ломтики говядины, овощи вок, соево-кунжутный соус, отварной рис.",
    "composition_kz": "Сиыр етінің тілімдері, вок көкөністері, соя-күнжіт соусы, пісірілген күріш.",
    "composition_en": "Sliced beef, wok vegetables, soy-sesame sauce, and steamed rice.",
    "note": ""
  },
  {
    "id": "8-9",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Бефстроганов",
    "name_kz": "Бефстроганов",
    "name_en": "Beef Stroganoff",
    "price": 3790,
    "weight": "350г",
    "composition_ru": "Нежная говядина в сливочно-грибном соусе с картофельным пюре.",
    "composition_kz": "Кілегейлі саңырауқұлақ соусындағы жұмсақ сиыр еті, картоп езбесімен бірге.",
    "composition_en": "Tender beef in a creamy mushroom sauce, served with mashed potatoes.",
    "note": ""
  },
  {
    "id": "8-10",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Курица в сырном соусе",
    "name_kz": "Ірімшік соусындағы тауық еті",
    "name_en": "Chicken in Cheese Sauce",
    "price": 3290,
    "weight": "350г",
    "composition_ru": "Куриное филе тушеное в густом сырном соусе.",
    "composition_kz": "Қою ірімшік соусында бұқтырылған тауық филесі.",
    "composition_en": "Chicken fillet braised in a rich cheese sauce.",
    "note": ""
  },
  {
    "id": "8-11",
    "category_ru": "Горячие блюда",
    "category_kz": "Ыстық тағамдар",
    "category_en": "Main Courses",
    "name_ru": "Жареный картофель с мясом",
    "name_kz": "Ет қосылған қуырылған картоп",
    "name_en": "Fried Potatoes with Meat",
    "price": 3290,
    "weight": "400г",
    "composition_ru": "Жареный картофель дольками с кусочками мяса, луком и чесноком.",
    "composition_kz": "Ет кесектері, пияз және сарымсақ қосылған қуырылған картоп тілімдері.",
    "composition_en": "Fried potato wedges with pieces of meat, onion, and garlic.",
    "note": ""
  },

  {
    "id": "9-1",
    "category_ru": "Шашлык на мангале",
    "category_kz": "Мангалдағы кәуап",
    "category_en": "Charcoal Grill",
    "name_ru": "Антрекот",
    "name_kz": "Антрекот",
    "name_en": "Beef Entrecôte",
    "price": 5990,
    "weight": "300г",
    "composition_ru": "Сочный говяжий антрекот на кости, маринованный по фирменному рецепту.",
    "composition_kz": "Фирмалық рецепт бойынша маринадталған сүйекті шырынды сиыр антрекоты.",
    "composition_en": "Juicy bone-in beef entrecôte marinated according to our signature recipe.",
    "note": ""
  },
  {
    "id": "9-2",
    "category_ru": "Шашлык на мангале",
    "category_kz": "Мангалдағы кәуап",
    "category_en": "Charcoal Grill",
    "name_ru": "Шашлык из баранины",
    "name_kz": "Қой етінің кәуабы",
    "name_en": "Lamb Shashlik",
    "price": 3990,
    "weight": "250г",
    "composition_ru": "Мякоть молодой баранины на углях, лук маринованный.",
    "composition_kz": "Көмірде дайындалған жас қой етінің жұмсағы, маринадталған пиязбен.",
    "composition_en": "Tender young lamb grilled over charcoal, served with pickled onion.",
    "note": ""
  },
  {
    "id": "9-3",
    "category_ru": "Шашлык на мангале",
    "category_kz": "Мангалдағы кәуап",
    "category_en": "Charcoal Grill",
    "name_ru": "Люля-кебаб",
    "name_kz": "Люля-кебаб",
    "name_en": "Lula Kebab",
    "price": 3490,
    "weight": "250г",
    "composition_ru": "Рубленый фарш из баранины / говядины со специями и зеленью.",
    "composition_kz": "Дәмдеуіштер мен көк шөптер қосылған қой / сиыр етінің туралған фаршы.",
    "composition_en": "Chopped lamb / beef seasoned with spices and fresh herbs.",
    "note": ""
  },
  {
    "id": "9-4",
    "category_ru": "Шашлык на мангале",
    "category_kz": "Мангалдағы кәуап",
    "category_en": "Charcoal Grill",
    "name_ru": "Шашлык из курицы",
    "name_kz": "Тауық кәуабы",
    "name_en": "Chicken Shashlik",
    "price": 2990,
    "weight": "250г",
    "composition_ru": "Нежное куриное филе на шпажке, мангал-маринад.",
    "composition_kz": "Шпажкаға тағылған жұмсақ тауық филесі, мангалға арналған маринадпен.",
    "composition_en": "Tender chicken fillet skewered and marinated for grilling.",
    "note": ""
  },
  {
    "id": "9-5",
    "category_ru": "Шашлык на мангале",
    "category_kz": "Мангалдағы кәуап",
    "category_en": "Charcoal Grill",
    "name_ru": "Крылья куриные BBQ",
    "name_kz": "BBQ тауық қанаттары",
    "name_en": "BBQ Chicken Wings",
    "price": 2990,
    "weight": "300г",
    "composition_ru": "Куриные крылья в пикантном соусе барбекю.",
    "composition_kz": "Ащылау барбекю соусындағы тауық қанаттары.",
    "composition_en": "Chicken wings in a spicy barbecue sauce.",
    "note": ""
  },
  {
    "id": "9-6",
    "category_ru": "Шашлык на мангале",
    "category_kz": "Мангалдағы кәуап",
    "category_en": "Charcoal Grill",
    "name_ru": "Утка на мангале",
    "name_kz": "Мангалдағы үйрек еті",
    "name_en": "Charcoal-Grilled Duck",
    "price": 4290,
    "weight": "250г",
    "composition_ru": "Ароматные кусочки утиного мяса на мангале.",
    "composition_kz": "Мангалда дайындалған хош иісті үйрек еті.",
    "composition_en": "Aromatic pieces of duck grilled over charcoal.",
    "note": ""
  },
  {
    "id": "9-7",
    "category_ru": "Шашлык на мангале",
    "category_kz": "Мангалдағы кәуап",
    "category_en": "Charcoal Grill",
    "name_ru": "Шашлык из куриного бедра",
    "name_kz": "Тауық сан етінің кәуабы",
    "name_en": "Chicken Thigh Shashlik",
    "price": 2990,
    "weight": "250г",
    "composition_ru": "Сочное мясо куриного бедра без кости.",
    "composition_kz": "Сүйексіз тауық санынан жасалған шырынды ет.",
    "composition_en": "Juicy boneless chicken thigh meat.",
    "note": ""
  },
  {
    "id": "9-8",
    "category_ru": "Шашлык на мангале",
    "category_kz": "Мангалдағы кәуап",
    "category_en": "Charcoal Grill",
    "name_ru": "Овощи на мангале",
    "name_kz": "Мангалдағы көкөністер",
    "name_en": "Charcoal-Grilled Vegetables",
    "price": 2490,
    "weight": "300г",
    "composition_ru": "Баклажан, кабачок, томаты, болгарский перец на углях.",
    "composition_kz": "Көмірде дайындалған баклажан, кәді, қызанақ және болгар бұрышы.",
    "composition_en": "Eggplant, zucchini, tomatoes, and bell pepper grilled over charcoal.",
    "note": ""
  },
  {
    "id": "9-9",
    "category_ru": "Шашлык на мангале",
    "category_kz": "Мангалдағы кәуап",
    "category_en": "Charcoal Grill",
    "name_ru": "Шампиньоны на мангале",
    "name_kz": "Мангалдағы шампиньондар",
    "name_en": "Charcoal-Grilled Mushrooms",
    "price": 2290,
    "weight": "250г",
    "composition_ru": "Шампиньоны в чесночном маринаде на углях.",
    "composition_kz": "Сарымсақ маринадындағы шампиньондар көмірде дайындалады.",
    "composition_en": "Champignons in a garlic marinade, grilled over charcoal.",
    "note": ""
  },

  {
    "id": "10-1",
    "category_ru": "Гарниры",
    "category_kz": "Гарнирлер",
    "category_en": "Side Dishes",
    "name_ru": "Овощи гриль",
    "name_kz": "Гриль көкөністері",
    "name_en": "Grilled Vegetables",
    "price": 1990,
    "weight": "250г",
    "composition_ru": "Микс сезонных овощей, приготовленных на гриле.",
    "composition_kz": "Грильде дайындалған маусымдық көкөністер миксі.",
    "composition_en": "A mix of seasonal vegetables prepared on the grill.",
    "note": ""
  },
  {
    "id": "10-2",
    "category_ru": "Гарниры",
    "category_kz": "Гарнирлер",
    "category_en": "Side Dishes",
    "name_ru": "Брокколи на пару",
    "name_kz": "Буға піскен брокколи",
    "name_en": "Steamed Broccoli",
    "price": 1790,
    "weight": "200г",
    "composition_ru": "Соцветия брокколи на пару.",
    "composition_kz": "Буға пісірілген брокколи гүлшоғырлары.",
    "composition_en": "Steamed broccoli florets.",
    "note": ""
  },
  {
    "id": "10-3",
    "category_ru": "Гарниры",
    "category_kz": "Гарнирлер",
    "category_en": "Side Dishes",
    "name_ru": "Картофель по-деревенски",
    "name_kz": "Ауылша картоп",
    "name_en": "Country-Style Potatoes",
    "price": 1590,
    "weight": "250г",
    "composition_ru": "Запеченный картофель с кожурой и специями.",
    "composition_kz": "Қабығымен және дәмдеуіштермен пісірілген картоп.",
    "composition_en": "Baked potatoes with skin and spices.",
    "note": ""
  },
  {
    "id": "10-4",
    "category_ru": "Гарниры",
    "category_kz": "Гарнирлер",
    "category_en": "Side Dishes",
    "name_ru": "Картофель фри",
    "name_kz": "Картоп фри",
    "name_en": "French Fries",
    "price": 1590,
    "weight": "200г",
    "composition_ru": "Классический картофель фри с солью.",
    "composition_kz": "Тұз қосылған классикалық картоп фри.",
    "composition_en": "Classic French fries with salt.",
    "note": ""
  },
  {
    "id": "10-5",
    "category_ru": "Гарниры",
    "category_kz": "Гарнирлер",
    "category_en": "Side Dishes",
    "name_ru": "Рис",
    "name_kz": "Күріш",
    "name_en": "Rice",
    "price": 1190,
    "weight": "180г",
    "composition_ru": "Отварной рассыпчатый рис.",
    "composition_kz": "Піскен, түйіршігі бөлек күріш.",
    "composition_en": "Fluffy steamed rice.",
    "note": ""
  },

  {
    "id": "11-1",
    "category_ru": "Соусы",
    "category_kz": "Соустар",
    "category_en": "Sauces",
    "name_ru": "Сырный",
    "name_kz": "Ірімшік соусы",
    "name_en": "Cheese Sauce",
    "price": 590,
    "weight": "50г",
    "composition_ru": "Фирменный сырный соус.",
    "composition_kz": "Фирмалық ірімшік соусы.",
    "composition_en": "Signature cheese sauce.",
    "note": ""
  },
  {
    "id": "11-2",
    "category_ru": "Соусы",
    "category_kz": "Соустар",
    "category_en": "Sauces",
    "name_ru": "Красный",
    "name_kz": "Қызыл соус",
    "name_en": "Red Sauce",
    "price": 590,
    "weight": "50г",
    "composition_ru": "Острый томатный соус с зеленью.",
    "composition_kz": "Көк шөптер қосылған ащы томат соусы.",
    "composition_en": "Spicy tomato sauce with fresh herbs.",
    "note": ""
  },
  {
    "id": "11-3",
    "category_ru": "Соусы",
    "category_kz": "Соустар",
    "category_en": "Sauces",
    "name_ru": "Белый",
    "name_kz": "Ақ соус",
    "name_en": "White Sauce",
    "price": 590,
    "weight": "50г",
    "composition_ru": "Чесночно-сметанный соус.",
    "composition_kz": "Сарымсақ пен қаймақтан жасалған соус.",
    "composition_en": "Garlic and sour cream sauce.",
    "note": ""
  },
  {
    "id": "11-4",
    "category_ru": "Соусы",
    "category_kz": "Соустар",
    "category_en": "Sauces",
    "name_ru": "Кетчуп",
    "name_kz": "Кетчуп",
    "name_en": "Ketchup",
    "price": 590,
    "weight": "50г",
    "composition_ru": "Классический томатный кетчуп.",
    "composition_kz": "Классикалық томат кетчупы.",
    "composition_en": "Classic tomato ketchup.",
    "note": ""
  },
  {
    "id": "11-5",
    "category_ru": "Соусы",
    "category_kz": "Соустар",
    "category_en": "Sauces",
    "name_ru": "Тартар",
    "name_kz": "Тартар соусы",
    "name_en": "Tartar Sauce",
    "price": 590,
    "weight": "50г",
    "composition_ru": "Соус на основе майонеза с солеными огурцами и зеленью.",
    "composition_kz": "Майонез негізіндегі тұздалған қияр мен көк шөптер қосылған соус.",
    "composition_en": "Mayonnaise-based sauce with pickles and fresh herbs.",
    "note": ""
  },

  {
    "id": "12-1",
    "category_ru": "Десерты",
    "category_kz": "Десерттер",
    "category_en": "Desserts",
    "name_ru": "Восточные сладости",
    "name_kz": "Шығыс тәттілері",
    "name_en": "Oriental Sweets",
    "price": 5490,
    "weight": "350г",
    "composition_ru": "Ассорти восточных десертов, пахлава, орехи.",
    "composition_kz": "Шығыс десерттерінің ассортиі, пахлава, жаңғақтар.",
    "composition_en": "Assortment of Oriental desserts, baklava, and nuts.",
    "note": ""
  },
  {
    "id": "12-2",
    "category_ru": "Десерты",
    "category_kz": "Десерттер",
    "category_en": "Desserts",
    "name_ru": "Пирожное в ассортименте",
    "name_kz": "Торттар ассортименті",
    "name_en": "Assorted Pastries",
    "price": 2590,
    "weight": "150г",
    "composition_ru": "Спросите официанта о доступных десертах дня.",
    "composition_kz": "Бүгінгі қолжетімді десерттер туралы даяшыдан сұраңыз.",
    "composition_en": "Ask your server about today's available desserts.",
    "note": ""
  },

  {
    "id": "13-1",
    "category_ru": "Безалкогольные напитки",
    "category_kz": "Алкогольсіз сусындар",
    "category_en": "Soft Drinks",
    "name_ru": "Фирменные лимонады",
    "name_kz": "Фирмалық лимонадтар",
    "name_en": "Signature Lemonades",
    "price": 2990,
    "weight": "400мл",
    "composition_ru": "Освежающий авторский напиток на основе свежих фруктовых пюре и газированной воды.",
    "composition_kz": "Жаңа піскен жеміс езбелері мен газдалған судан дайындалған сергітетін авторлық сусын.",
    "composition_en": "Refreshing signature drink made with fresh fruit purées and sparkling water.",
    "note": "Вишня-Виноград, Киви-Грейпфрут, Жасмин, Маракуйя-Ананас, Нектар"
  },
  {
    "id": "13-2",
    "category_ru": "Безалкогольные напитки",
    "category_kz": "Алкогольсіз сусындар",
    "category_en": "Soft Drinks",
    "name_ru": "Авторский чай",
    "name_kz": "Авторлық шай",
    "name_en": "Signature Tea",
    "price": 2590,
    "weight": "600мл",
    "composition_ru": "Фирменный чайный микс с добавлением свежих фруктов, ягод и трав.",
    "composition_kz": "Жаңа піскен жемістер, жидектер және шөптер қосылған фирмалық шай қоспасы.",
    "composition_en": "Signature tea blend with fresh fruits, berries, and herbs.",
    "note": "Алматинский, Ташкентский, Малина-Лайм, Персик-жасмин"
  },
  {
    "id": "13-3",
    "category_ru": "Безалкогольные напитки",
    "category_kz": "Алкогольсіз сусындар",
    "category_en": "Soft Drinks",
    "name_ru": "Пепси",
    "name_kz": "Пепси",
    "name_en": "Pepsi",
    "price": 1790,
    "weight": "330мл",
    "composition_ru": "Газированный безалкогольный напиток.",
    "composition_kz": "Газдалған алкогольсіз сусын.",
    "composition_en": "Carbonated soft drink.",
    "note": ""
  },
  {
    "id": "13-4",
    "category_ru": "Безалкогольные напитки",
    "category_kz": "Алкогольсіз сусындар",
    "category_en": "Soft Drinks",
    "name_ru": "Листовой чай",
    "name_kz": "Жапырақты шай",
    "name_en": "Loose Leaf Tea",
    "price": 1590,
    "weight": "600мл",
    "composition_ru": "Элитный листовой чай на выбор.",
    "composition_kz": "Таңдауыңыз бойынша премиум жапырақты шай.",
    "composition_en": "Premium loose-leaf tea of your choice.",
    "note": "Ассам, Сенча, Жасмин, Эрл Грей, Ройбуш, Султан"
  },

  {
    "id": "14-1",
    "category_ru": "Вино",
    "category_kz": "Шарап",
    "category_en": "Wine",
    "name_ru": "Blanc de Blancs Tete de Cheval",
    "name_kz": "Blanc de Blancs Tete de Cheval",
    "name_en": "Blanc de Blancs Tete de Cheval",
    "price": 14990,
    "weight": "750мл",
    "composition_ru": "Игристое вино, легкий утонченный вкус.",
    "composition_kz": "Жеңіл әрі нәзік дәмі бар жарқыраған шарап.",
    "composition_en": "Sparkling wine with a light and refined taste.",
    "note": "Игристое белое, бутылка"
  },

  {
    "id": "15-1",
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka",
    "name_ru": "Koskenkorva",
    "name_kz": "Koskenkorva",
    "name_en": "Koskenkorva",
    "price": 2090,
    "weight": "50мл",
    "composition_ru": "Финская водка премиум-класса.",
    "composition_kz": "Финляндиялық премиум санаттағы арақ.",
    "composition_en": "Premium Finnish vodka.",
    "note": "50 г"
  },
  {
    "id": "15-2",
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka",
    "name_ru": "Mont Blanc",
    "name_kz": "Mont Blanc",
    "name_en": "Mont Blanc",
    "price": 2690,
    "weight": "50мл",
    "composition_ru": "Французская водка из пшеницы.",
    "composition_kz": "Бидайдан жасалған француз арағы.",
    "composition_en": "French vodka made from wheat.",
    "note": "50 г"
  },
  {
    "id": "15-3",
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka",
    "name_ru": "Архангельская Северная",
    "name_kz": "Архангельская Северная",
    "name_en": "Arkhangelskaya Severnaya",
    "price": 1790,
    "weight": "50мл",
    "composition_ru": "Классическая мягкая водка.",
    "composition_kz": "Классикалық жұмсақ арақ.",
    "composition_en": "Classic smooth vodka.",
    "note": "50 г"
  },
  {
    "id": "15-4",
    "category_ru": "Водка",
    "category_kz": "Арақ",
    "category_en": "Vodka",
    "name_ru": "Белуга Нобл",
    "name_kz": "Белуга Нобл",
    "name_en": "Beluga Noble",
    "price": 2690,
    "weight": "50мл",
    "composition_ru": "Российская премиальная водка.",
    "composition_kz": "Ресейлік премиум арақ.",
    "composition_en": "Premium Russian vodka.",
    "note": "50 г"
  },

  {
    "id": "16-1",
    "category_ru": "Пиво бутылочное",
    "category_kz": "Бөтелкедегі сыра",
    "category_en": "Bottled Beer",
    "name_ru": "Ayinger, Brauweisse",
    "name_kz": "Ayinger, Brauweisse",
    "name_en": "Ayinger, Brauweisse",
    "price": 2990,
    "weight": "500мл",
    "composition_ru": "Немецкое пшеничное нефильтрованное пиво.",
    "composition_kz": "Немістің сүзілмеген бидай сырасы.",
    "composition_en": "German unfiltered wheat beer.",
    "note": "Нефильтрованное"
  },
  {
    "id": "16-2",
    "category_ru": "Пиво бутылочное",
    "category_kz": "Бөтелкедегі сыра",
    "category_en": "Bottled Beer",
    "name_ru": "Ayinger, Lager",
    "name_kz": "Ayinger, Lager",
    "name_en": "Ayinger, Lager",
    "price": 2990,
    "weight": "500мл",
    "composition_ru": "Традиционный немецкий лагер.",
    "composition_kz": "Дәстүрлі неміс лагері.",
    "composition_en": "Traditional German lager.",
    "note": "Фильтрованное"
  },
  {
    "id": "16-3",
    "category_ru": "Пиво бутылочное",
    "category_kz": "Бөтелкедегі сыра",
    "category_en": "Bottled Beer",
    "name_ru": "Gubernija Brown Ale",
    "name_kz": "Gubernija Brown Ale",
    "name_en": "Gubernija Brown Ale",
    "price": 1990,
    "weight": "500мл",
    "composition_ru": "Тёмный эль с карамельными нотками.",
    "composition_kz": "Карамельді реңктері бар қою эль.",
    "composition_en": "Dark ale with caramel notes.",
    "note": "Тёмное"
  },
  {
    "id": "16-4",
    "category_ru": "Пиво бутылочное",
    "category_kz": "Бөтелкедегі сыра",
    "category_en": "Bottled Beer",
    "name_ru": "Gubernija Ekstra Lager",
    "name_kz": "Gubernija Ekstra Lager",
    "name_en": "Gubernija Ekstra Lager",
    "price": 1990,
    "weight": "500мл",
    "composition_ru": "Светлое пиво классической варки.",
    "composition_kz": "Классикалық әдіспен қайнатылған ашық сыра.",
    "composition_en": "Classic-style pale lager.",
    "note": "Фильтрованное"
  },

  {
    "id": "17-1",
    "category_ru": "Пиво разливное",
    "category_kz": "Құйма сыра",
    "category_en": "Draft Beer",
    "name_ru": "Holsten Pilsener",
    "name_kz": "Holsten Pilsener",
    "name_en": "Holsten Pilsener",
    "price": 1890,
    "weight": "500мл",
    "composition_ru": "Светлое разливное пиво.",
    "composition_kz": "Ашық түсті құйма сыра.",
    "composition_en": "Pale draft beer.",
    "note": "Светлое фильтрованное"
  },
  {
    "id": "17-2",
    "category_ru": "Пиво разливное",
    "category_kz": "Құйма сыра",
    "category_en": "Draft Beer",
    "name_ru": "Kronenbourg Blanc",
    "name_kz": "Kronenbourg Blanc",
    "name_en": "Kronenbourg Blanc",
    "price": 2290,
    "weight": "500мл",
    "composition_ru": "Французское пшеничное пиво с фруктовыми нотками.",
    "composition_kz": "Жемісті реңктері бар француз бидай сырасы.",
    "composition_en": "French wheat beer with fruity notes.",
    "note": "Нефильтрованное"
  },

];
